### ISSUE TITLE
feature request, is it possible to add an option to specify a room?

### ISSUE THREAD

**Issue by peterb99** [naofireblade/homebridge-weather-plus#101]
Is it possible to specify a 'room' in the json config?
Currently all items show up under 'default' room.
I would like to show the up in a separate 'room', like for instance 'MyLocation'

**Comment by naofireblade** [comment]
Ye, you can add multiple stations for different cities: https://github.com/naofireblade/homebridge-weather-plus/blob/master/README.md#multiple-stations-configuration
