### ISSUE TITLE
No accessories shown in new EVE app 4.2 /w Homebridge beta

### ISSUE THREAD

**Issue by palasinio** [naofireblade/homebridge-weather-plus#106]
Hi,

I'm testing the actual Homebridge betas like shown here:
https://github.com/homebridge/homebridge/issues/2459

With the latest EVE App 4.2 I cannot see any accessories.
In Apples Home app everything is okay exept one point:
"Dew Point" accessories show "unavailable" if "Dew Point" == "0".

Maybe you can have a look at it?

**Comment by naofireblade** [comment]
The plugin in version 3.1.1 works fine for me with homebridge v1.0.3. Do you still experience any problems with the final release?

**Comment by palasinio** [comment]
@naofireblade: Funny, now it’s working. I had to deselect all weather-plus items on EVE favorites page and hide all items in the room and then selecting things again. I‘m using the option to show all stuff in Home app, too. Thanks.

**Comment by palasinio** [comment]
PS: But didn‘t have a dew point of 0 right now... so I can‘t sayyid sure....

**Comment by naofireblade** [comment]
Thanks for the fast reply. I will close the issue and you can comment if the dew point problem occurs.
