### ISSUE TITLE
DarkSky registration not possible any more?

### ISSUE THREAD

**Issue by morphix9** [naofireblade/homebridge-weather-plus#108]
Hey guys, after selling to Apple, DarkSky is not accepting new registrations anymore. Is there a way to use Dark Sky anyways?

**Comment by naofireblade** [comment]
Sadly not (as far as I know). You could use OpenWeatherMap meanwhile.

**Comment by naofireblade** [comment]
I updated the readme to reflect the shut down of dark sky for new users :( .
