### ISSUE TITLE
Multiple weather stations

### ISSUE THREAD

**Issue by BeauGiles** [naofireblade/homebridge-weather-plus#11]
Is there any possibility to add multiple 'accessories', either in it's current form in the config or with some changes?

It would be useful to have multiple weather stations, for example a 'local' one, as well as a city, or perhaps another personal weather station elsewhere.

**Comment by naofireblade** [comment]
That sounds like a great feature. It is currently not possible but I will look into a solution.

**Comment by simont77** [comment]
@naofireblade I can work on this if you want

**Comment by naofireblade** [comment]
Sure, that would be great. I added you as a collaborator so you don't need to wait for me to merge your PRs.

**Comment by simont77** [comment]
Thanks, It may involve some deep refactoring, I will work on a new branch

**Comment by simont77** [comment]
@naofireblade I finished adding the multiple stations feature in the new branch. Please review it and let me know. I could not test yahoo API. Changelog is still to be updated.

**Comment by naofireblade** [comment]
Sorry I had a really busy week, I will test everything and rewrite the readme a bit on the weekend.
