### ISSUE TITLE
Add new OpenWeatherMap API with many more observation and forecast values

### ISSUE THREAD

**Issue by naofireblade** [naofireblade/homebridge-weather-plus#114]
- [x] - Replace old API dependency with an own request

- [x] - DewPoint
- [x] - TemperatureWindChill
- [x] - UVIndex
- [x] - CloudCover
- [x] - Rain1h
- [x] - RainDay
- [x] - Sunrise
- [x] - Sunset
- [x] - More forecast days

**Comment by chrisjshull** [comment]
Is this for the new "One Call API"?
https://openweathermap.org/api/one-call-api

**Comment by naofireblade** [comment]
Yes. You can test the beta with: `npm install -g homebridge-weather-plus@beta`
