### ISSUE TITLE
Unknown OpenWeatherMap category 201

### ISSUE THREAD

**Issue by ggiese2000** [naofireblade/homebridge-weather-plus#116]
After installing the Plugins works fine - kudos.

Only I get the reoccurring error:
`Unknown OpenWeatherMap category 201`
and also:
`Unknown OpenWeatherMap category 200`
my config.json:
`  {`
`          "platform": "WeatherPlus",`
`          "service": "openweathermap",`
`           "key": "xxxxxxxxxxxx",`
`           "locationId": 2855745,`
`           "locationCity": "Paderborn, DE",`
`           "locationGeo": [`
`              xxxx,`
`              xxxx`
`          ],`
`            "compatibility": "both",`
`            "conditionCategory": "detailed",`
`            "forecast": [`
`                0,`
`                1`
`            ],`
`            "hidden": [`
`                "CloudCover",`
`                "DewPoint"`
`           ],`
`           "interval": 5,`
`            "language": "en",`
 `          "nameNow": "Paderborn",`
 `           "nameForecast": "Paderborn Forecast",`
  `          "now": true,`
   `         "units": "metric"`
`        }`

**Comment by naofireblade** [comment]
Thanks!
