### ISSUE TITLE
Tiny error in example on page

### ISSUE THREAD

**Issue by ggiese2000** [naofireblade/homebridge-weather-plus#117]
Hi, Just stumbled on a small error on your example:
[ https://www.npmjs.com/package/homebridge-weather-plus# ](url)
says:
`        "units": "metric",`
`    }`
`]`

I am pretty sure the comma will cause an error, so the correct version should read
`        "units": "metric"`
`    }`
`]`

**Comment by naofireblade** [comment]
Thanks!
