### ISSUE TITLE
Cannot make automation on temperature sensor

### ISSUE THREAD

**Issue by santheman-nl** [naofireblade/homebridge-weather-plus#118]
I have implemented this plugin and it shows my Weather Underground info, such as temperature etc.
2 things I can't seem to figure out:
1. Once I want to make an automation, I don't see the temperature sensor (only the others like wind direction etc.) But I want an automation based on temperature.
2. I don't understand the thresholds. What is their purpose and what do I fill in? 

Thank you for your help.

**Comment by naofireblade** [comment]
Hi,
1. The apple home app is incapable of creating automations based on temperature sensors. You need to use a 3rd party homekit app like "Eve" for that.
2. The apple home app is incabable of showing other sensors then temperature/humidity. So if you set compatibility to "home", the plugin adds occupancy sensors for the other values as a workaround. The treshold defines at which value the sensor will change from off to on. You can use that state in automations.

**Comment by santheman-nl** [comment]
> The treshold defines at which value the sensor will change from off to on. You can use that state in automations
But there is no scale? So I don't know what to fill in?

Thanks for your reply

**Comment by naofireblade** [comment]
You can define the tresholds in your [config file](https://github.com/naofireblade/homebridge-weather-plus#advanced-configuration) or with config-ui-x.

In homekit rules you just check if the sensor is on or off.

**Comment by santheman-nl** [comment]
I know where to define them, but I wonder what the values are. 
For example cloud cover, is that in percentages? Or a 0 to 5 value?

**Comment by naofireblade** [comment]
I understand. I will add that in the documentation.

**Comment by santheman-nl** [comment]
Thank you for your help!

**Comment by naofireblade** [comment]
I added the explanation in the readme: https://github.com/naofireblade/homebridge-weather-plus#advanced-configuration

**Comment by santheman-nl** [comment]
Great! Thanks
