### ISSUE TITLE
Details from OpenWeatherMap are shown as presence sensor -can this be changed?

### ISSUE THREAD

**Issue by richardk2016** [naofireblade/homebridge-weather-plus#120]
I set up your wonderful plugin with OpenWeatherMap. 

But now all additional informations are shown as presence sensors. As seen on the screenshot from Eve-App. 

![20-05-06 00-59-53 5066](https://user-images.githubusercontent.com/18516984/81124627-30536880-8f36-11ea-8008-9fad3b78068d.png)

Homebridge Version: 1.0.4 
Node.js Version: v12.16.3 
Npm Version: v6.14.4 

Config:
```
{
            "units": "ca",
            "interval": 4,
            "stations": [
                {
                    "nameNow": "[YES]",
                    "service": "openweathermap",
                    "key": "[YES]",
                    "locationId": [YES],
                    "language": "de",
                    "compatibility": "both",
                    "forecast": [
                        "Today",
                        "Tomorrow",
                        "In 2 days"
                    ],
                    "nameForecast": "Vorschau",
                    "conditionCategory": "simple",
                    "now": true,
                    "extraHumidity": false
                }
            ],
            "platform": "WeatherPlus"
}
```
 I want the informatation but not the Anwesend / Abwesend indication. Can this be chnaged? Is there a better way to display the information?

**Comment by naofireblade** [comment]
The presence sensors are just for compatibility with the default "Home" app from apple. If you are using eve, you can set "compatibility" to "eve" instead of "both".

**Comment by naofireblade** [comment]
Feel free to reopen if you still have questions.
