### ISSUE TITLE
Error when installed the plugin for homebridge

### ISSUE THREAD

**Issue by mimes123** [naofireblade/homebridge-weather-plus#123]
Hi my homebridge can't reboot after i installed the plugin. so i have to uninstall it again.
what can i do ?

here is a picture of the log

**Comment by mimes123** [comment]
<img width="1213" alt="Skærmbillede 2020-05-15 kl  14 32 07" src="https://user-images.githubusercontent.com/65078292/82098885-28e64900-9706-11ea-8784-9c91b42ca882.png">

**Comment by Naqsaq** [comment]
I have the same issue but with "TypeError: Cannot read property 'pressure' of undefined". What's going on?

**Comment by naofireblade** [comment]
@mimes123 your config is missing a weather service. Please use the config-ui-x editor or the example config in the readme.

**Comment by naofireblade** [comment]
@Naqsaq looks like your weather response contains no weather data. Can you share your config (without apikey)?

**Comment by Naqsaq** [comment]
> @Naqsaq looks like your weather response contains no weather data. Can you share your config (without apikey)?

I used the config-ui-x editor for the config. Didn't do any manual edits. I did use the "both" compatibility option. Seems to be working fine when switching to "home" after reinstalling now. Will report back later if the problem comes back with the "both".

**Comment by mimes123** [comment]
I tried with the example in readme with my own api did not change anything was still crashing

**Comment by mimes123** [comment]
it is working now thanks.
one more question is it possible to see the min and max temp of the day and the windspeed in the Homekit app on every forecast and now ?
