### ISSUE TITLE
Apparent Temperature is always reported in Celsius

### ISSUE THREAD

**Issue by name99-org** [naofireblade/homebridge-weather-plus#151]
I have Weather Plus set up to use Fahrenheit. (Yes, I know, sigh, but I'm in the US and it's just easier to match everyone else.)

For the most part this works fine, but the Apparent Temperature appears to always be reported in Celsius, not Fahrenheit; eg right now Current Temp is reported as 81 deg F, Apparent Temp as 25 deg F, which makes no sense, but converted from C to F is 77 deg F which is reasonable. 

If it matters, my data provider is OpenWeatherMap, I'm viewing the values in Eve, and the other options that may be relevant are 
"compatibility": "eve",
"conditionCategory": "simple",

**Comment by naofireblade** [comment]
This should be fixed in v3.2.4. Can you confirm this?

**Comment by name99-org** [comment]
Sorry, I got distracted and forgot to reply to you about this!
Yes, as far as I can tell, it's now working correctly :-)
If I noticed any other weirdness next time I try to create ambitious automation, I'll let you know.

Thanks,
Maynard
