### ISSUE TITLE
No translation to Dutch

### ISSUE THREAD

**Issue by thezjo** [naofireblade/homebridge-weather-plus#158]
Great plug-in, only problem I see is that it does not translate to Dutch.
I do have the default english language in both Homebridge and Homekit
My config looks like below and so I was expecting to get a Dutch translation
Thanks for any help.
{
            "units": "si",
            "interval": 10,
            "stations": [
                {
                    "nameNow": "Mijn Weer",
                    "service": "openweathermap",
                    "key": “xxxxxxxxxxxxxxxxxxxxx”,
                    "locationCity": "Asten, NL",
                    "language": "nl",
                    "compatibility": "both",
                    "conditionCategory": "detailed",
                    "now": true,
                    "extraHumidity": false
                }
            ],
            "platform": "WeatherPlus"
        },

**Comment by naofireblade** [comment]
The language option currently only affects the weather description and not any labels.
