### ISSUE TITLE
Language question

### ISSUE THREAD

**Issue by exrabies** [naofireblade/homebridge-weather-plus#161]
How or where do I install an alternative language? Can't find it anywhere in the description of this plugin (which is amazing btw ;-).

Homebridge running on Rasperry Pi buster.

**Comment by frans2526** [comment]
Hello,

You can change the language in your config file, just below « locationcity ».
Or in the settings plugins below the coordinates.

Bye

**Comment by exrabies** [comment]
Thanx for the ultra quick reply. I'll try to explain my situation, and rephrase the question. I'm using HomeKit and HomeBridge to 'automate' a holiday home we rent out. We have English, French and Dutch customers. I'm looking for a way to address these customers in their own language. This specific plugin is very useful, but translation looks a bit half ways. Some parts of the interface remain in English. Hence my question. Can I, as a user, change the language of the interface (more than the added language files can).

**Comment by frans2526** [comment]
I think you wont be able to get much more because the language you set into the JSON or in the plugin is coming from the API so basically homebridge-weather-plus is simply showing you what they received from openweathermap. 
you can still code something yourself.

This is my guess after looking a bit deeper into the code to try to fix my issue.

**Comment by naofireblade** [comment]
Yes the language option currently affects only the weather description. If I find the time, I might add translations for the labels.

**Comment by naofireblade** [comment]
You can check the progress of localisation here: https://github.com/naofireblade/homebridge-weather-plus/issues/50
Currently I have no free time for that issue :/ .
