### ISSUE TITLE
Dew Point Temperature Bug

### ISSUE THREAD

**Issue by nicoryan** [naofireblade/homebridge-weather-plus#162]
My OAT is 23 degrees. My JSON file is configured correctly for multiple stations. For some reason my Dew Point and Apparent Temperature displays in 5 digits and is completely erroneous. I am using Imperial Units. The Dew Point is 23 out but Weather Plus displays 65532 F. Any idea why this would be displaying this way?

I have a Weather Flow Tempest hooked into Weather Underground and am using Openweather for forecasting. Both display this erroneous Dew Point temp. 

Looking for any assistance please.

**Comment by frans2526** [comment]
Hello,

I have the same issue on EVE app, I think this is maybe related to my issue (Bug Temperature at or below 0 Home App not working). Do you know if our dew point or your apparent temperature should be below 0°C ?

Thanks

**Comment by nicoryan** [comment]
It might be. It's cold here. Hasn't been above 32 since I configured the JSON. I am not sure what the problem could be but there is definitely a bug somewhere.

**Comment by frans2526** [comment]
I juste spend 4hours trying to understand how it works and I found the request to openweathermap are made in metric which shouldn’t be an issue(the value are correctly converted) but it seems to be.
For my issue, I think I found it the issue, homebridge can only simulate a temperature between 0-100. This why when we arrived below 0C homebridge is bugging and not the plugin.

**Comment by frans2526** [comment]
Hi nicoryan, I was able to resolve my bug but unfortunately on EVE app my apparent temperature is still showing 65535 so I am not sure from where this bug is coming.

**Comment by nicoryan** [comment]
@frans2526 yep this is definitely a bug associated with the temperature dropping below 0 F. Today it is 35 F (above freezing) outside and the dew point and apparent temperature are reading normally. 

This is definitely a big associated with the temperature dropping below 0 F. 

Hopefully the plugin developer will see this and inspect the code to determine why the erroneous temperatures are displayed in 5 digits when the outside temperature drops below 0 F.

**Comment by kylerove** [comment]
I created a pull request to merge fix suggested by @frans2526. https://github.com/naofireblade/homebridge-weather-plus/pull/167

**Comment by naofireblade** [comment]
Fixed in v3.2.3
