### ISSUE TITLE
Apparent temperature frequently shown as unresponding in Home app

### ISSUE THREAD

**Issue by chernals** [naofireblade/homebridge-weather-plus#163]
I have a configuration with a single weather station, current situation + next-day forecast. All is working fine, except for the apparent temperature which is almost all the time shown as "unresponding" in the Home app.

Would this be a known issue ?

I'm in the compatibility configuration "both".

**Comment by frans2526** [comment]
Hello,

I made a quick fix for this issue event if isn’t the proper way to do it but at least we will be able to see the temperature when they are below 0C on home app.
You can check my post : #160

Cheers

**Comment by chernals** [comment]
Thanks ! Noob questioN: Not sure what I have to do from #160  . Is that a change in the weather plugin config ?

**Comment by kylerove** [comment]
I created a pull request to merge fix suggested by @frans2526. https://github.com/naofireblade/homebridge-weather-plus/pull/167

**Comment by MontroseSt** [comment]
@chernals on a Mac the path to the plugins is /usr/local/lib/node_modules
you can also find the path in terminal
`cd $(npm -g prefix)/lib/node_modules`
`pwd`

@kylerove thank you, working perfectly!

**Comment by naofireblade** [comment]
Fixed in v3.2.3
