### ISSUE TITLE
OpenWeather - excessive calls

### ISSUE THREAD

**Issue by prophet42** [naofireblade/homebridge-weather-plus#164]
I received this message from OpenWeather: "We have noticed that your account is currently using One Call API quite intensively and exceed the account limit of 1000 calls per day." I am only using it for this homebridge plugin. Does that seem accurate? Is there a way to limit the calls? Thanks!

**Comment by naofireblade** [comment]
Can u post your plugin config (without api key) please?

**Comment by prophet42** [comment]
Hi. Sure, I have pasted it below. I've uninstalled Weather Plus for now, as I could not resolve it. I tried generating a new API key, in case someone somehow got ahold of my key and was using it for something else, but that did not help. OpenWeather let me know that I went from about 360 calls per day to about 8600 calls per day on Dec. 20. I did not make any changes to my config at that time. Thanks for your help.

        {
            "platform": "WeatherPlus",
            "service": "openweathermap",
            "key": "APIkey",
            "locationGeo": [
                49.25657395,
                -122.89168239
            ],
            "conditionCategory": "detailed",
            "forecast": [
                0
            ]
        },

**Comment by valiquette** [comment]
I am having the same issue and received the same email, nothing in my configuration has changed.

        {
            "units": "us",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "Winter Park",
                    "service": "openweathermap",
                    "key": "xyzzy",
                    "locationCity": "Fraser, CO, US",
                    "language": "en",
                    "compatibility": "home",
                    "conditionCategory": "detailed",
                    "now": true,
                    "extraHumidity": false,
                    "tresholdAirPressure": 1050,
                    "tresholdCloudCover": 3,
                    "tresholdUvIndex": 6,
                    "tresholdWindSpeed": 10
                }
            ],
            "platform": "WeatherPlus"
        },

**Comment by MAPEZ1** [comment]
I received also the eMail just yesterday at 23:51 that I have exceeded 1000 calls per day 🤷🏼‍♂️ 

>>
One Call API usage alert

Dear Customer!

Thank you for choosing OpenWeather[https://openweathermap.org/]!

We have noticed that your account is currently using One Call API[https://openweathermap.org/api/one-call-api] quite intensively and exceed the account limit of 1000 calls per day.
>>

Config (see below) is set to call every 5 minutes - means 288 times in 24h
I started to use it on Oct. 18 to Nov. 22, then a break (raspi down) and again from Dec. 13
No issues so far - except the 1000 exceed mail.
Will keep it running / monitoring.

Is there a possibility to get a more detailed log ?
When it was triggered and with wich result?

{
            "units": "si",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "WWWeather",
                    "service": "openweathermap",
                    "key": "xxxxxyyyyyzzzzzz123",
                    "locationCity": "xxxxxyyyyyzzzzz, DE",
                    "language": "de",
                    "compatibility": "both",
                    "conditionCategory": "simple",
                    "now": true,
                    "extraHumidity": false,
                    "hidden": [
                        "Condition",
                        "Condition Category",
                        "Dew Point",
                        "Forecast Day",
                        "Observation Station",
                        "Observation Time",
                        "Ozone",
                        "Snow",
                        "Temperature Min",
                        "Temperature Apparent",
                        "UV Index",
                        "Visibility",
                        "Wind Speed Max"
                    ]
                },
                {
                    "nameNow": "Forecast",
                    "service": "openweathermap",
                    "key": "xxxxyyyyyzzzz1234",
                    "locationCity": "xxxxyyyyzzzz, DE",
                    "language": "de",
                    "compatibility": "both",
                    "forecast": [
                        "Tomorrow"
                    ],
                    "nameForecast": "+ ",
                    "conditionCategory": "simple",
                    "now": false,
                    "extraHumidity": false,
                    "hidden": [
                        "Condition",
                        "Condition Category",
                        "Dew Point",
                        "Observation Station",
                        "Observation Time",
                        "Ozone",
                        "Snow",
                        "Temperature Min",
                        "Temperature Apparent",
                        "UV Index",
                        "Visibility",
                        "Wind Speed Max"
                    ]
                }
            ],
            "platform": "WeatherPlus"
        },

**Comment by valiquette** [comment]
I forgot to mention I am running on 1.3.0 beta42

**Comment by MAPEZ1** [comment]
#135 Same issue with some more info.
Thanks @loudgazelle for providing info on ticket.
Has someone the possibility to provide code for logging the calls
so that we can get / provide more info from homebridge / weather-plus?

**Comment by MAPEZ1** [comment]
Update from my side.... it seems not to happen anymore.
Might have been an OpenWeather issue....

**Comment by prophet42** [comment]
Hi,

Thanks for the update. I may give it another try.

Matt

**Comment by dacarson** [comment]
Seems like the issue has solved itself.
Closing.
