### ISSUE TITLE
Temperature sensor not responding on Apple Home App

### ISSUE THREAD

**Issue by mrMiimo** [naofireblade/homebridge-weather-plus#168]
I just updated to the latest version (3.2.3) but temperature sensor still doesn't work ...
I think because the temperature is negative .. To test I set a weatherStation (ISANTAFE65) with positive temperature and it works.

Someone can help me please?
Thx

This is debug mode (wunderground):

omebridge-weather-plus {
homebridge-weather-plus "observations": [
homebridge-weather-plus {
homebridge-weather-plus "stationID": "IMEZZO9",
homebridge-weather-plus "obsTimeUtc": "2020-12-28T10:25:40Z",
homebridge-weather-plus "obsTimeLocal": "2020-12-28 11:25:40",
homebridge-weather-plus "neighborhood": "Mezzocorona",
homebridge-weather-plus "softwareType": "EasyWeatherV1.5.6",
homebridge-weather-plus "country": "IT",
homebridge-weather-plus "solarRadiation": 0.9,
homebridge-weather-plus "lon": 11.131,
homebridge-weather-plus "realtimeFrequency": null,
homebridge-weather-plus "epoch": 1609151140,
homebridge-weather-plus "lat": 46.216,
homebridge-weather-plus "uv": 0,
homebridge-weather-plus "winddir": 83,
homebridge-weather-plus "humidity": 95,
homebridge-weather-plus "qcStatus": -1,
homebridge-weather-plus "metric_si": {
homebridge-weather-plus "temp": -2.2,
homebridge-weather-plus "heatIndex": -2.2,
homebridge-weather-plus "dewpt": -2.9,
homebridge-weather-plus "windChill": -2.2,
homebridge-weather-plus "windSpeed": 0,
homebridge-weather-plus "windGust": 0,
homebridge-weather-plus "pressure": 987.81,
homebridge-weather-plus "precipRate": 0,
homebridge-weather-plus "precipTotal": 0,
homebridge-weather-plus "elev": 66.8
homebridge-weather-plus }
homebridge-weather-plus }
homebridge-weather-plus ]
homebridge-weather-plus } +2s
homebridge-weather-plus Units: s +3ms
homebridge-weather-plus Current Conditions for station 'Now': {
homebridge-weather-plus ObservationStation: 'IMEZZO9 : Mezzocorona',
homebridge-weather-plus ObservationTime: Moment<2020-12-28T11:25:40+01:00>,
homebridge-weather-plus WindDirection: 'E',
homebridge-weather-plus Humidity: 95,
homebridge-weather-plus SolarRadiation: 0.9,
homebridge-weather-plus UVIndex: 0,
homebridge-weather-plus Temperature: -2.2,
homebridge-weather-plus DewPoint: -2.9,
homebridge-weather-plus AirPressure: 987.81,
homebridge-weather-plus WindSpeed: 0,
homebridge-weather-plus WindSpeedMax: 0,
homebridge-weather-plus RainDay: 0
homebridge-weather-plus } +2s
homebridge-weather-plus Setting Humidity to 95 +9ms
homebridge-weather-plus Setting Temperature to -2.2 +2ms
homebridge-weather-plus Saving history entry +4ms

**Comment by mrMiimo** [comment]
#166

**Comment by naofireblade** [comment]
Thanks for reporting, I'm working on a fix right now.

**Comment by naofireblade** [comment]
Fixed in v3.2.4

**Comment by mrMiimo** [comment]
Yes! Confirmed.
Thanks for that @naofireblade
