### ISSUE TITLE
Temperature Displays Incorrectly Below 32F

### ISSUE THREAD

**Issue by nicoryan** [naofireblade/homebridge-weather-plus#170]
Installed the most recent update 3.2.4 which supposedly was supposed to correct the temperature bug for the apparent temperature and dew point.

Bug is still present. Now instead of temperatures displaying in 4 digits. The temperature displays in 2 digits. However, it’s obviously incorrect. For example. It is 30F outside right now. Dew Point and Apparent Temperature both are indicating above 79F.

This is an obvious bug. If it’s 30F outside.... No way is the Dew Point and Apparent Temp 79F.

@naofireblade

**Comment by joconor** [comment]
It looks like perhaps it is doing the conversion twice. 79F would be 26.1C which would be a reasonable _Fahrenheit_ reading for dew point and/or apparent temp.

I'm attaching a screenshot from the Eve app where my current temp is 53F, but dew point shows 109F and apparent temp shows 128.5F. Converted to celsius, those would be 42.8 & 53.6.

![IMG_6AAE1C075EFA-1](https://user-images.githubusercontent.com/116850/103431834-64e1f780-4b8b-11eb-9122-37b643ef234b.jpeg)

**Comment by joberembt** [comment]
I'm also having this problem. It's currently 25 out, with a dewpoint of 19 but the plugin is saying that the dewpoint is 66.2 - no way this is possible.

**Comment by naofireblade** [comment]
Hey, could u please check if the temperature is still wrong? This issue is a bit tricky because in the past HomeKit did not convert values for custom characteristics like dew point and I had to convert it manually. But it seems like HomeKit does this conversion now by itself.
