### ISSUE TITLE
Weather Categories

### ISSUE THREAD

**Issue by judas2720** [naofireblade/homebridge-weather-plus#171]
What are the mappings between the weather-plus Condition Categories and the OpenWeatherMap Condition Categories? I am looking specific for thunderstorms (OWM ["Group 2xx: Thunderstorm"](https://openweathermap.org/weather-conditions#Weather-Condition-Codes-2)) but I don't seem to see where they map to in in the plugin categories?

**Comment by naofireblade** [comment]
You can find the general categories in the readme. For specific OWM Code Mapping look into this file: https://github.com/naofireblade/homebridge-weather-plus/blob/52117ddb03e9fca0003686836427a22ad081c699/apis/openweathermap.js#L176
