### ISSUE TITLE
Installation Issues - HOOBS

### ISSUE THREAD

**Issue by barnwern** [naofireblade/homebridge-weather-plus#172]
I keep on getting installation issues f trying to install the Plugin in HOOBS

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/object-assign: Integrity verification failed for sha512-XiOL/8zfa3vgV/pVfiOrDD9jcbkUhgJKdH4eG0BdeUoSLzpjwL4fR9k30vut4fy35E2V7Y6bhqpE09FEJ+EjfA== (/home/hoobs/.npm/_cacache/content-v2/sha512/5e/23/8bffccdf6b7be057fa557e23ab0c3f6371b91486024a747e1e1b405d794a122f3a63c0be1f47d937d2fbade1fcb7e44d95ed8e9b86aa44d3d14427e1237c)
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-01-01T12_22_22_052Z-debug.log

**Comment by daydy16** [comment]
Had the same issue when installing via the ui.
I fixed it by installing via command line (docker exec ...) and then it showed my the real error message.
After running: "npm install --save --force homebridge-weather-plus@latest" it works for me

**Comment by dacarson** [comment]
Closing as there are no new reported issues that match this issue.
