### ISSUE TITLE
Temperature below 0 Celcius not reported properly in home main screen

### ISSUE THREAD

**Issue by pelletip** [naofireblade/homebridge-weather-plus#173]
<img width="700" alt="Screen Shot 2021-01-04 at 9 16 20 AM" src="https://user-images.githubusercontent.com/76956192/103544895-c4335680-4e6e-11eb-8582-14046e320c7e.png">

Temperature below zero celcius are reported in a weird way on the main home screen, but they look fine once you expand the climate section.

**Comment by naofireblade** [comment]
This looks like an issue in HomeKit itself.
