### ISSUE TITLE
No condition choice for some values

### ISSUE THREAD

**Issue by bambuk6** [naofireblade/homebridge-weather-plus#177]
First, many thanks for the plugin!
I am trying to create automation using some values exposed by the plugin; however, the problem is that not all of them allow a choice of condition. E.g, in the Eve app Air Pressure does:
![F83456DB-0B03-45F8-BE48-EF421131FBF5](https://user-images.githubusercontent.com/15034720/104927192-1b592100-596f-11eb-8007-b41d3786534c.jpeg)

But Solar Radiation does not:
![1F890A86-1743-461F-8272-0C86A00B8450](https://user-images.githubusercontent.com/15034720/104927210-21e79880-596f-11eb-9869-5928652fc76e.jpeg)

What is the reason? Can it be fixed?

**Comment by naofireblade** [comment]
This can only be fixed by the eve app itself.
