### ISSUE TITLE
Feels Like Temperature and Dew Point Temperatures Wrong

### ISSUE THREAD

**Issue by plutod73** [naofireblade/homebridge-weather-plus#178]
I noticed the range of temperatures displayed in the Home app, and confirmed in the Eve app show invalid temperatures for both feels like and dew point. The dew point on OpenWeather is correct; however, the plugin value is not. My configuration is as follows:

      {
            "units": "us",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "Home",
                    "service": "openweathermap",
                    "key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    "locationCity": "Winter Garden, US",
                    "language": "en",
                    "compatibility": "home",
                    "conditionCategory": "detailed",
                    "now": true,
                    "extraHumidity": true,
                    "tresholdCloudCover": 75,
                    "tresholdUvIndex": 8
                }
            ],
            "platform": "WeatherPlus"
        }

![Screen Shot 2021-01-18 at 5 35 24 AM](https://user-images.githubusercontent.com/77647330/104971235-20908d00-59bc-11eb-940b-15319d097cf2.png)
![Screen Shot 2021-01-18 at 5 36 10 AM](https://user-images.githubusercontent.com/77647330/104971240-238b7d80-59bc-11eb-8d2f-4f98149adbb6.png)

**Comment by naofireblade** [comment]
Should be fixed in v3.2.5
