### ISSUE TITLE
Plug-in doesn't seem to poll again after initial startup

### ISSUE THREAD

**Issue by threeonparfive** [naofireblade/homebridge-weather-plus#179]
My poling interval is setup to the default of 5 which I've confirmed in config.json.  I see WeatherPlus pulling the station at initial start up and no other activity in the Homebridge log after that.  I have the wind speed threshold set to 10 (which was below what was current speed at startup time....it was 15 at startup).  This triggered the occupancy sensor as expected on startup and the sensor shows 15 in HomeKit.  Per the data for this station on OpenWeatherMap's website, the wind speed has dropped down to 11 yet the sensor still shows 15 in HomeKit....and it's been over an hour since the speed dropped to 11 yet still no change.  At this point, I can't really even believe the sensor will reset to "off" even once the wind drops to below 10 since there's no evidence suggesting the plug-in is even polling.

**Comment by threeonparfive** [comment]
Ok....I decided to change weather stations which of course required a restart.  At that time, wind speed was 1mph and reflected as such in HomeKit.  A little while later, the sensor trigger and I verified on Openweathermap that wind speed was indeed measured back over 10.  However, I look in HomeKit and even though the sensor triggered, the wind speed reflected in HomeKit still read 1.  So it seems the real issue here is the HomeKit wind speed never gets update.....ever...after initial startup even though apparently the sensor is triggering on or off on polling updates.

**Comment by naofireblade** [comment]
Homekit itself does not support many weather characteristics like wind etc. I found a hack by renaming the sensor after each update. But this renaming might fail in some setups (maybe your HomeKit server etc. I cannot narrow that one.) A solution would be to use compatibility mode eve and the eve app. That app supports wind as a real characteristic.
