### ISSUE TITLE
Missing rain value in forecasts from dark sky API when a day is skipped in config

### ISSUE THREAD

**Issue by MBarti** [naofireblade/homebridge-weather-plus#187]
from the logs:

[2/21/2021, 3:34:32 PM] [homebridge-weather-plus] This plugin generated a warning from the characteristic 'Air Pressure': characteristic was supplied illegal value: number 1024 exceeded maximum of 255. See https://git.io/JtMGR for more info.
[2/21/2021, 3:34:32 PM] [homebridge-weather-plus] This plugin generated a warning from the characteristic 'Ozone': characteristic was supplied illegal value: number 309 exceeded maximum of 255. See https://git.io/JtMGR for more info.

**Comment by naofireblade** [comment]
What version of the plug-in are u using?

**Comment by Nastras** [comment]
Hi @naofireblade 

I use the ltest version and get this hint.

![8FA466A8-EE8E-4443-AEA2-62ED21C3D61A](https://user-images.githubusercontent.com/27686185/108804751-6c77b880-759e-11eb-93e6-c8c7b01202fa.jpeg)

**Comment by naofireblade** [comment]
Thanks for reporting. Will fix that asap.

**Comment by naofireblade** [comment]
I tried to reproduce the error but I had no success. Can you post your plugin config? Could you also set the environment variable DEBUG to "homebridge-weather-plus" in Homebridge UI Settings?

**Comment by Nastras** [comment]
"platforms": [
{
"platform": "WeatherPlus",
"service": "darksky",
"key": "xxxxx",
"location": [xx.xxxxxx, x.xxxxxx],
"language": "de",
"units": "metric",
"interval": 5,
"conditionCategory": "detailed",
"compatibility": "eve",
"nameNow": "Wetteraktuell",
"nameForecast": "Wettervorhersage",
"hidden": [],
"forecast": [1]
}
]
}

**Comment by Nastras** [comment]
Debug mode I have just switched on. Waiting for the error to occur 😉

**Comment by Nastras** [comment]
![5F26CD14-1983-450B-8E96-104CCC4D04D3](https://user-images.githubusercontent.com/27686185/112368219-2025b280-8cdb-11eb-8d17-4a4429334a9c.jpeg)

**Comment by Nastras** [comment]
Is that enough for you or do you need a longer log?
If so, I would provide it to you in the Smart Apple forum?

**Comment by naofireblade** [comment]
That should be enough.

**Comment by Nastras** [comment]
👍

**Comment by naofireblade** [comment]
That one was hard to nail down. The rain forecast with dark sky has a bug when u skip some days. You only want the forecast for the next day (1) and not the one for today (0). That causes a bug in the plugin.

**Comment by Nastras** [comment]
Cool that you were able to determine it. What exactly do I have to change in the config so that this bug no longer occurs? Thx!

**Comment by naofireblade** [comment]
You can just add the 0 to the forecasts so that you get the forecast for today and tomorrow.
´"forecast": [0,1]´
Or wait until I publish the fix.

**Comment by Nastras** [comment]
All right then, I'll add the 0 for now. Thanks for the help!

**Comment by naofireblade** [comment]
I released version 3.2.6 that fixes your issue.
