### ISSUE TITLE
error with WUnderground

### ISSUE THREAD

**Issue by UKGman** [naofireblade/homebridge-weather-plus#189]
I am getting a JSON error when trying to use the WUnderground API

[WeatherPlus] Error retrieving weather report and forecast
[WeatherPlus] Error Message: SyntaxError: Unexpected end of JSON input

with the config

        {
            "units": "si",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "Bromley",
                    "service": "weatherunderground",
                    "key": "cbbb61c3b6c64125bb61c3b6c66125ee",
                    "stationId": "iBromley15",
                    "language": "en",
                    "compatibility": "both",
                    "conditionCategory": "detailed",
                    "now": true,
                    "extraHumidity": true,
                    "tresholdWindSpeed": 10
                }
            ]
            "platform": "WeatherPlus"
        }

**Comment by Alfarache** [comment]
Seeing this as well.

**Comment by UKGman** [comment]
> Seeing this as well.
> 
> This was caused by my weather station being unplugged and not sending data to weather underground.

My issue was that the weather station was case sensitive, I need to use the name from my profile, not what I use to search in WUnderground.

now working :)

**Comment by petcol** [comment]
I've just set up the weather station and I can see it's report correctly to Weatherunderground but my HomeBridge is the error message
[WeatherPlus] Error Message: SyntaxError: Unexpected end of JSON input
followed by
[WeatherPlus] Error retrieving weather report and forecast
repeated
