### ISSUE TITLE
How are you using OccupancyDetected with Wind data?

### ISSUE THREAD

**Issue by modellbobby** [naofireblade/homebridge-weather-plus#191]
Hi,

i am searching a way to send wind speeds to home bridge and did not find a suitable service yet. 
I found your implementation but don't understand how you can send wind speed data to https://developers.homebridge.io/#/service/OccupancySensor

Can you explain please?

**Comment by naofireblade** [comment]
When using compatibility mode "home", I create an occupancy sensor for wind speeds and enable this sensor if the current wind speed is above the configured wind speed threshold. I also update the name of the sensor to reflect the wind speed value.
