### ISSUE TITLE
New? Error 

### ISSUE THREAD

**Issue by mbierman** [naofireblade/homebridge-weather-plus#193]
I don't recall seeing this error before. 

```
[3/4/2021, 1:03:44 AM] [homebridge-weather-plus] This plugin generated a warning from the characteristic 'Air Pressure': Characteristic not in required or optional characteristic section for service TemperatureSensor. Adding anyway.. See https://git.io/JtMGR for more info.
```

**Enviornment**
* **Node.js Version**: 14.16.0
* **NPM Version**: 7.6.0
* **Homebridge Version**: 1.3.1
* **Homebridge Config UI X Version**: v4.39.1
* **Operating System**: Docker
* **Process Supervisor**: Docker
* **Alpine Linux**:3.12.3

**Comment by naofireblade** [comment]
Hi can you post your plugin config? Without apikey and location.

**Comment by Lorccan** [comment]
I am getting the same error. Here's the config:

`{
            "units": "si",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "Home",
                    "service": "openweathermap",
                    "key": "XXXXXXXXXXXXXXXXXXXXXXXX",
                    "locationGeo": [
                        XX.XXXX,
                        -X.XXXX
                    ],
                    "locationCity": "XXXX",
                    "language": "en",
                    "compatibility": "eve",
                    "forecast": [
                        "Today",
                        "Tomorrow"
                    ],
                    "conditionCategory": "simple",
                    "now": true,
                    "extraHumidity": false,
                    "hidden": [
                        "Cloud Cover",
                        "Condition",
                        "Condition Category",
                        "Dew Point",
                        "Humidity",
                        "Observation Station",
                        "Observation Time",
                        "Ozone",
                        "Rain 1h",
                        "Rain Chance",
                        "Snow",
                        "Solar Radiation",
                        "Sunrise Time",
                        "Sunset Time",
                        "Temperature Min",
                        "Temperature Apparent",
                        "UV Index",
                        "Visibility",
                        "Wind Direction",
                        "Wind Speed",
                        "Wind Speed Max"
                    ]
                }
            ],
            "_bridge": {
                "username": "XX:XX:XX:XX:XX:XX",
                "port": 39916
            },
            "platform": "WeatherPlus"
        }`

**Comment by TeslaOwnerTips** [comment]
[1/21/2023, 2:15:37 PM] [homebridge-weather-plus] This plugin generated a warning from the characteristic 'Air Pressure': Characteristic not in required or optional characteristic section for service TemperatureSensor. Adding anyway.. See https://homebridge.io/w/JtMGR for

[config_json.txt](https://github.com/naofireblade/homebridge-weather-plus/files/10472866/config_json.txt)

[info_json.txt](https://github.com/naofireblade/homebridge-weather-plus/files/10472868/info_json.txt)

[plugins_json.txt](https://github.com/naofireblade/homebridge-weather-plus/files/10472869/plugins_json.txt)
 more info.

**Comment by dacarson** [comment]
Duplicate #206
