### ISSUE TITLE
Max temperature not shown?

### ISSUE THREAD

**Issue by vandenbogerd** [naofireblade/homebridge-weather-plus#195]
I tried all compatibilities: eve, home, both, but I can not get Max Temp to show (in Eve and Home).

I want to create a trigger in the morning: if the max temp of that day will be 25°C, then close all screens already.

**Comment by naofireblade** [comment]
Temperature in forecasts is max temperature :) .

**Comment by vandenbogerd** [comment]
![IMG_0989](https://user-images.githubusercontent.com/57765237/113263993-c15fca80-92d2-11eb-8972-f07c790f2b51.jpg)
I doubt that...

**Comment by naofireblade** [comment]
Thats "now" (current conditions) and not a forecast. You can configure forecasts report in the plugin. Even for the current day.

**Comment by vandenbogerd** [comment]
I did. Checked "Today" under "Forecast"

**Comment by vandenbogerd** [comment]
Crap, it was located to the standard room... my bad... n00b!
