### ISSUE TITLE
Darksky timeout

### ISSUE THREAD

**Issue by zany92** [naofireblade/homebridge-weather-plus#202]
Hello,

Since few days, I can't get DarkSky API update (my account was registered in 2019, my API key is valid)
Error Message: Forecast cannot be retrieved. ERROR: Error: ETIMEDOUT

Is it the end of DarkSky API or is it something else?
Thanks

**Comment by dacarson** [comment]
It is the end of DarkSky. Support for it has been removed.

I would recommend using [OpenWeatherMap](https://openweathermap.org/price#weather). It offers a free subscription.
