### ISSUE TITLE
only temp shows not solar or wind or rain Oliver 

### ISSUE THREAD

**Issue by oliverchapple** [naofireblade/homebridge-weather-plus#210]
hi 

I have added weatherplus to hoobs 4 with my weather underground key.

but it only shows the temp not wind solar rain etc on the  accessories screen 

what I would like to know is how do make them all show not just the temp.

from Oliver

**Comment by dacarson** [comment]
To make the others show up in the Apple's Home app you need to make sure that you have [compatibility](https://github.com/naofireblade/homebridge-weather-plus?tab=readme-ov-file#advanced-configuration) set to `home` or `both`. And use `3.3.5` or later.

**Comment by dacarson** [comment]
Closing as stale.
