### ISSUE TITLE
Threshold UV index does not work?

### ISSUE THREAD

**Issue by emcepe** [naofireblade/homebridge-weather-plus#212]
for whatever reason the threshold for UV index does not work.

I've set it to 6 but Homebridge shows occupancy with value of 0.

I thought the bug is the typo of tresholdUvIndex because of the missing h after t but after editing the config and changing it to thresholdUvIndex it won't work either.

I'm using weatherunderground as API, with Homebridge 1.3.4 and newest plugin version v3.2.6

thanks.

**Comment by dacarson** [comment]
There were bugs in threshold handling. 
Can you paste your config here and I can verify it?

**Comment by emcepe** [comment]
Hi David,

only if it doesn't take another 3 years for you to reply again 🤣

**Comment by dacarson** [comment]
Hi,
Thanks for your feedback. I've only recently got involved in this project as an open source contributor. Using my limited skills I am just trying to help and make the product better. I actually only use the Tempest weather station, but thought while I'm working on the code, I'll take a look at some of the issues.
If you are still running into issues, I could look into to it for you. 
David

**Comment by dacarson** [comment]
I believe this is the same issue as #122.
If it is a problem still after #122 has been resolved, please re-open.
