### ISSUE TITLE
Hanging on install

### ISSUE THREAD

**Issue by JimmyEyeball** [naofireblade/homebridge-weather-plus#216]
Hi I have been trying to re-install Weather-Plus after a  Homebridge rebuild and it seems to be hanging at the same point each time please see screenshot below

Timezone | GMT+0100
Microsoft Windows 10 Pro
W10-Homebridge
v14.17.6
SYSTEM
C:\Users\Homebridge\.homebridge
C:\Users\Homebridge\.homebridge\config.json
Yes

![image](https://user-images.githubusercontent.com/50030249/134387102-1e5eeb3b-28cc-495c-b8f6-706ca8111dd8.png)

**Comment by ctrlcmdshft** [comment]
im having same issue with it hanging on install

**Comment by n0hot** [comment]
Same issue:

Alpine Linux (3.12.8) 
Node.js Version  v14.17.6
Npm Version  v6.14.15
Docker

**Comment by JimmyEyeball** [comment]
Yes direct through NPM and not config UI worked but still had to leave it sitting for 30-45min or so for it to complete.

**Comment by dacarson** [comment]
No additional reports of this issue. 
Closing.
