### ISSUE TITLE
Choosing Imperial units not honored

### ISSUE THREAD

**Issue by DifferentComputers** [naofireblade/homebridge-weather-plus#232]
I select "Imperial" units in settings for my location, but the accessories all show metric. I've changed the setting, reselected, restarted the server, and no change.

**Comment by rossvarrette** [comment]
Same here.

**Comment by dacarson** [comment]
How are you viewing the values?
The units settings only impact the 'compatibility' sensors which show the values as part of the label.
For sensors that are native (eg temperature, humidity), their units are set by the application that you are using to view the values.

**Comment by dacarson** [comment]
As mentioned in this [comment](https://github.com/naofireblade/homebridge-weather-plus/issues/259#issuecomment-1936733055), the units are only used for Apple Home ("_home_") [compatibility mode](https://github.com/naofireblade/homebridge-weather-plus?tab=readme-ov-file#compatibility) sensors. 

The units that are viewed via HomeKit are set by the application/iOS device. 

Closing this issue as resolved/behaves correctly.
