### ISSUE TITLE
Home not displaying precipitation value?

### ISSUE THREAD

**Issue by DoinitSideways** [naofireblade/homebridge-weather-plus#233]
Value is seen in homebridge… and temp and humidity are working fine and showing the value in HomeKit… not sure what’s wrong with the HomeKit?
![B5D11931-80FE-43B3-889C-69C2590C67EC](https://user-images.githubusercontent.com/95604443/155719924-320f379e-9eb9-4605-a41f-12030793b490.jpeg)
![09D83B2D-AB6E-40DF-9905-86CE05972B6E](https://user-images.githubusercontent.com/95604443/155719934-cc5779e3-0886-40be-8fd3-c0864c053e33.jpeg)

**Comment by naofireblade** [comment]
I cannot control when the Home app decides to update the name (value) of the accessory.
