### ISSUE TITLE
Characteristic was supplied illegal value: number 11 exceeded maximum of 10

### ISSUE THREAD

**Issue by egakagoc2xi** [naofireblade/homebridge-weather-plus#235]
Settings:
`{
    "accessories": [],
    "platforms": [
        {
            "platform": "WeatherPlus",
            "interval": 5,
            "units": "ca",
            "stations": [
                {
                    "key": "XXXXXXXXXXXXXXXXXXX",
                    "service": "openweathermap",
                    "locationGeo": [
                        19.06026688,
                        -96.08144978
                    ],
                    "compatibility": "both",
                    "language": "es",
                    "nameForecast": "Punta Tiburon",
                    "conditionCategory": "detailed",
                    "now": true,
                    "extraHumidity": true,
                    "thresholdWindSpeed": 40
                }
            ]
        }
    ]
}
[LogWeatherPlus.docx](https://github.com/naofireblade/homebridge-weather-plus/files/8429634/LogWeatherPlus.docx)
`

**Comment by ElphaX** [comment]
Related to #201, perhaps?

**Comment by naofireblade** [comment]
Fixed in v3.2.7
