### ISSUE TITLE
Conditions categories set to 4 but Eve shows 9 options

### ISSUE THREAD

**Issue by rsuaver** [naofireblade/homebridge-weather-plus#236]
I set up conditions categories to 4 via the GUI but in the Eve app, it shows 9 possible options.  I tested on a cloudy day and it would trigger only if >=3 instead of >=1.

Config is set to "simple"
```
{
    "units": "us",
    "interval": 5,
    "stations": [
        {
            "nameNow": "Home",
            "service": "openweathermap",
            "language": "en",
            "compatibility": "both",
            "conditionCategory": "simple",
            "now": true,
            "extraHumidity": false,
            "hidden": [
                "Air Pressure",
                "Dew Point",
                "Ozone",
                "UV Index",
                "Visibility"
            ]
        }
    ],
    "platform": "WeatherPlus"
}
```

**Comment by dacarson** [comment]
The Eve app will always show 9 possible options (0 - 9). I believe very old versions of Eve were limited to 4.
That said, it should still work as the Eve app just looks at the number. 

Can you send me a screenshot of your automation? I am not an expert in it, but can take a look.

My test below works. I read it as:
"When Condition Category changes to '1' (aka [simple](https://github.com/naofireblade/homebridge-weather-plus?tab=readme-ov-file#a3) === 'overcast'), and it is after Sunrise then turn on the Office Light".

![IMG_60037FE47F3B-1](https://github.com/naofireblade/homebridge-weather-plus/assets/44933987/d6cd9ea4-590b-4d27-bc1d-f6de1ef07863)

**Comment by dacarson** [comment]
Closing as stale.
