### ISSUE TITLE
Error retrieving weather report and forecast

### ISSUE THREAD

**Issue by daguchan** [naofireblade/homebridge-weather-plus#238]
The plugin stopped working a week or so back with the following errors:

[6/4/2022, 11:50:41] [WeatherPlus] Error retrieving weather report and forecast
[6/4/2022, 11:50:41] [WeatherPlus] Error Message: SyntaxError: Unexpected end of JSON input

There were no additions or updates made to the system, it just stopped working. I have updated both homebridge and Weather Plus but still experiencing this issue. Any insight into the problem?

**Comment by NossieUK** [comment]
I'm having the exact same isssue sadly =( any joy with it?

**Comment by dacarson** [comment]
I believe this is fixed. Can you try with the latest version. If it is still a problem, please file a new issue and include the JSON configuration. 
Thanks
