### ISSUE TITLE
With Eve compatibility, not all fields are available. I need sunrise/sunset.

### ISSUE THREAD

**Issue by lmolter54** [naofireblade/homebridge-weather-plus#240]
This plug-in is great and I *will* leave coffee money eventually; however, I need the local sunrise and sunset times (they are unchecked in the properties) but they are not in the payload.

**Comment by Jogistar** [comment]
check the field "forecast today" and you will get a forecast for today with sunrise and sunset.. 👍😎

**Comment by lmolter54** [comment]
Hmmm... not so. I have 'forecast' set to Today and I don't get a sunrise or
sunset time in the payload. If I use the Node-red node OpenWeatherMap In, I
get the sunrise and sunset times. For now, I use a Node-red node to tell me
whether or not it's Day or Night where I live. I really don't need the
exact times.

[image: image.png]
*Larry*

**Comment by Jogistar** [comment]
I use home+ 5 app for iOS, i dont know how the EVE app shows data
I have my setup as followed: (homebridge & home+5 image attached in link)
link to wetransfer
[https://we.tl/t-qNv9chikgp](url)

**Comment by dacarson** [comment]
I assume you are using [Openweather API v2.5](https://openweathermap.org/current)
It seems sunrise and sunset are part of the spec. for the current weather, as well as the [forecast](https://openweathermap.org/forecast5) API. I am not sure why support for it wasn't added. 
I'll post a patch that adds support for it.

**Comment by dacarson** [comment]
@Jogistar may have got sunrise and sunset for the forecast as the code was there for OpenWeather v3.0 API. However, it wasn't there for current weather. And it was totally missing when v2.5 API was used

**Comment by dacarson** [comment]
Unfortunately, I don't have a v3.0 API account, so I can't verify that it is working. @Jogistar if there is a way you could test my change, I would appreciate it.
Or @jkreileder I believe you have a v3.0 account, I'd it if you could validate my code.

**Comment by jkreileder** [comment]
@dacarson The 3.0 API provides sunset und sunrise for both the current day and forecasts.  The code so far only used the values for forecasts.  I've opened a PR that also uses them for the current day.

**Comment by dacarson** [comment]
Thanks @jkreileder. I also have fixed it on my fork, and was hoping to get it tested. If your PR lands first, I will just merge it with mine that also reports Sunrise and Sunset for 2.5 API.

**Comment by dacarson** [comment]
Can you please try `3.3.4-beta.1` and verify that it works.

**Comment by dacarson** [comment]
I believe this is fixed. Try `3.3.4` or later.
