### ISSUE TITLE
Alternative weather API

### ISSUE THREAD

**Issue by Meteosource** [naofireblade/homebridge-weather-plus#242]
Hello,
I would like to ask you, whether you would be interested in integration with another weather API - [https://www.meteosource.com/](https://www.meteosource.com/). If this is something you would be interested in, I will fork the repository, implement the integration and then submit a pull request.

Thank you for your response,
Meteosource team

**Comment by DeutscheMark** [comment]
"You can add more services easily by forking the project and submitting a pull request for a new api file."

**Comment by naofireblade** [comment]
Hi, a PR with a new service would be appreciated.

**Comment by Spy-1** [comment]
Thanks for the updates!
I now only get predictions for 4 days. Day 5,6 and 7 all have 0 degrees.

I also get the following long message in the log:
`[12/29/2022, 5:48:51 PM] [WeatherPlus] [
  [
    {
      dt: 1672336800,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.92,
      rain: [Object],
      sys: [Object],
      dt_txt: '2022-12-29 18:00:00'
    },
    {
      dt: 1672347600,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 9290,
      pop: 0.93,
      rain: [Object],
      sys: [Object],
      dt_txt: '2022-12-29 21:00:00'
    },
    {
      dt: 1672358400,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.91,
      rain: [Object],
      sys: [Object],
      dt_txt: '2022-12-30 00:00:00'
    },
    {
      dt: 1672369200,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.11,
      sys: [Object],
      dt_txt: '2022-12-30 03:00:00'
    },
    {
      dt: 1672380000,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.09,
      sys: [Object],
      dt_txt: '2022-12-30 06:00:00'
    },
    {
      dt: 1672390800,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2022-12-30 09:00:00'
    },
    {
      dt: 1672401600,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2022-12-30 12:00:00'
    },
    {
      dt: 1672412400,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 1,
      rain: [Object],
      sys: [Object],
      dt_txt: '2022-12-30 15:00:00'
    }
  ],
  [
    {
      dt: 1672423200,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 1,
      rain: [Object],
      sys: [Object],
      dt_txt: '2022-12-30 18:00:00'
    },
    {
      dt: 1672434000,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.99,
      rain: [Object],
      sys: [Object],
      dt_txt: '2022-12-30 21:00:00'
    },
    {
      dt: 1672444800,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.99,
      rain: [Object],
      sys: [Object],
      dt_txt: '2022-12-31 00:00:00'
    },
    {
      dt: 1672455600,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.17,
      sys: [Object],
      dt_txt: '2022-12-31 03:00:00'
    },
    {
      dt: 1672466400,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.23,
      rain: [Object],
      sys: [Object],
      dt_txt: '2022-12-31 06:00:00'
    },
    {
      dt: 1672477200,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2022-12-31 09:00:00'
    },
    {
      dt: 1672488000,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2022-12-31 12:00:00'
    },
    {
      dt: 1672498800,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2022-12-31 15:00:00'
    }
  ],
  [
    {
      dt: 1672509600,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2022-12-31 18:00:00'
    },
    {
      dt: 1672520400,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2022-12-31 21:00:00'
    },
    {
      dt: 1672531200,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-01 00:00:00'
    },
    {
      dt: 1672542000,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-01 03:00:00'
    },
    {
      dt: 1672552800,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-01 06:00:00'
    },
    {
      dt: 1672563600,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-01 09:00:00'
    },
    {
      dt: 1672574400,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-01 12:00:00'
    },
    {
      dt: 1672585200,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-01 15:00:00'
    }
  ],
  [
    {
      dt: 1672596000,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-01 18:00:00'
    },
    {
      dt: 1672606800,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-01 21:00:00'
    },
    {
      dt: 1672617600,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-02 00:00:00'
    },
    {
      dt: 1672628400,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-02 03:00:00'
    },
    {
      dt: 1672639200,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-02 06:00:00'
    },
    {
      dt: 1672650000,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-02 09:00:00'
    },
    {
      dt: 1672660800,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-02 12:00:00'
    },
    {
      dt: 1672671600,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-02 15:00:00'
    }
  ],
  [
    {
      dt: 1672682400,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2023-01-02 18:00:00'
    },
    {
      dt: 1672693200,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.04,
      sys: [Object],
      dt_txt: '2023-01-02 21:00:00'
    },
    {
      dt: 1672704000,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 9169,
      pop: 0.5,
      rain: [Object],
      sys: [Object],
      dt_txt: '2023-01-03 00:00:00'
    },
    {
      dt: 1672714800,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.77,
      rain: [Object],
      sys: [Object],
      dt_txt: '2023-01-03 03:00:00'
    },
    {
      dt: 1672725600,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.71,
      rain: [Object],
      sys: [Object],
      dt_txt: '2023-01-03 06:00:00'
    },
    {
      dt: 1672736400,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.13,
      sys: [Object],
      dt_txt: '2023-01-03 09:00:00'
    },
    {
      dt: 1672747200,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0.38,
      rain: [Object],
      sys: [Object],
      dt_txt: '2023-01-03 12:00:00'
    },
    {
      dt: 1672758000,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 8228,
      pop: 0.75,
      rain: [Object],
      sys: [Object],
      dt_txt: '2023-01-03 15:00:00'
    }
  ]
]`
Is there any way to turn this off?

**Comment by dacarson** [comment]
According to the original ask:

> I would like to ask you, whether you would be interested in integration with another weather API - https://www.meteosource.com/. If this is something you would be interested in, I will fork the repository, implement the integration and then submit a pull request.

The reply from the maintainer was:
> Hi, a PR with a new service would be appreciated.

So closing this as resolved as instructions were provided. Fork & Pull requests are appreciated.
