### ISSUE TITLE
Weather Report and Forecast Retrieval Error

### ISSUE THREAD

**Issue by iJasonWade** [naofireblade/homebridge-weather-plus#246]
WeatherUnderground:
`[homebridge-weather-plus] Error retrieving weather report and forecast`
`[homebridge-weather-plus] Error Message: SyntaxError: Unexpected token < in JSON at position 0`

**Comment by vrchlabak** [comment]
The same issue here.... Thanks!

**Comment by dacarson** [comment]
@iJasonWade is this issue still happening? If so, can you turn on debugging and add logs to this report.

**Comment by dacarson** [comment]
I have seen this error. In my case, I was getting an empty response (status code 204), and when examining [My Devices](https://www.wunderground.com/member/devices), I see that the station with the Station Id that I was using was marked as `offline`.
I will submit a PR that will make debugging this issue easier. 

Can you verify that your station is not offline.

**Comment by dacarson** [comment]
I believe this is fixed. Closing.
