### ISSUE TITLE
iOS 16 broke functionality in Homekit

### ISSUE THREAD

**Issue by vskal** [naofireblade/homebridge-weather-plus#247]
All tiles are misnamed after the update, they all display the name of the area.
Tried by renaming the tiles but the weather values do not pass trhough.

Could you please have a look !

**Comment by byna** [comment]
Same problem for me.
Is there a way we can help by activating logs or something?

**Comment by AdeTheux** [comment]
Yes, same. About 10 tiles with the local area name, and they all seem related to the temperature.

**Comment by Tomcraft1980** [comment]
Same problem here. All sensors are name "Wetterdaten" after updating to iOS 16. Before I had the sensors named like "Coud Cover" or "Wind" or "UV Index".

**Comment by naofireblade** [comment]
That’s a HomeKit problem I can’t do anything about. You could use the eve app or hide some sensors via the plug-in config

**Comment by lint2015** [comment]
> Same problem here. All sensors are name "Wetterdaten" after updating to iOS 16. Before I had the sensors named like "Coud Cover" or "Wind" or "UV Index".
> Seems to be related to issue #234.

I found that the final releases of iOS 16 provide a fix for this issue. If you delete the name of each of the sensors that now have the same name, it will default back to the sensor name that weather-plus initially assigned to them. I managed to fix all my sensor names this way.

**Comment by Tomcraft1980** [comment]
I am on iOS 16.2 and if I delete I see the default names as you said but if I leave the name field the name of the sensor fills out the name like before.
Where do you delete these names!?

**Comment by AdeTheux** [comment]
> > Same problem here. All sensors are name "Wetterdaten" after updating to iOS 16. Before I had the sensors named like "Coud Cover" or "Wind" or "UV Index".
> > Seems to be related to issue #234.
> 
> I found that the final releases of iOS 16 provide a fix for this issue. If you delete the name of each of the sensors that now have the same name, it will default back to the sensor name that weather-plus initially assigned to them. I managed to fix all my sensor names this way.

Thanks! That worked.
Clicking the "x" next to the accessory name, then typing something in worked for all sensors.

**Comment by Tomcraft1980** [comment]
Sure I can also rename them, but [lint2015](https://github.com/lint2015) said clicking the "x" would default back to the sensor name and this does not happen in my case.
Any suggestions?

**Comment by jens-vonberg** [comment]
It might be because the **serial number is the same on all the sensors**. When I overwrite the name, it sets them back to the station name immediately.

**Comment by naofireblade** [comment]
> It might be because the **serial number is the same on all the sensors**. When I overwrite the name, it sets them back to the station name immediately.

The serial number is the same because it is the same physician device. I could split up all sensors into different devices but that would result in 120 devices if you have 8 days and 15 sensors. Maybe as an option…

**Comment by steffmatj** [comment]
Hi!

thanks for the work on the plug-in!! I have the same issue with the labels not showing in iOS 16 HomeKit. Another plug-in found a solution to fix it.

They wrote the following in the release notes in the update that fixed it:

„Added Configured Name characteristic to the Switch, Stateless Programmable Switch, and Lightbulb services. This appears to be necessary for HomeKit on iOS 16 to show anything other than the accessory name without manually changing all of the names within the Home app.“

maybe you can look into it again and also try to fix it! Thank you!!

the plug-in is the following https://github.com/thoukydides/homebridge-homeconnect

best
Steff

**Comment by naofireblade** [comment]
Thanks. I will look into this.

**Comment by dacarson** [comment]
Following the example mentioned above, it seems that we need to use ConfiguredName when updating the tile with the current value.

**Comment by dacarson** [comment]
When I fix the issue, you can't see the values for a number of the sensors because of the UI of the Home app. Similar issue in the Eve app. Open on ideas on how to improve this.
(Ignore the "Now" sensor, as that is my Tempest Weather Station.) 

![IMG_4925](https://github.com/naofireblade/homebridge-weather-plus/assets/44933987/2b3372ac-d0f1-45c6-bd4d-e48c68b6fc98)
![IMG_4924](https://github.com/naofireblade/homebridge-weather-plus/assets/44933987/692591ac-e181-47bf-b5e0-89d2b0b595a9)
![IMG_4923](https://github.com/naofireblade/homebridge-weather-plus/assets/44933987/01d6508e-dff2-4299-b971-fae097028dab)
![IMG_4D12FFF996A9-1](https://github.com/naofireblade/homebridge-weather-plus/assets/44933987/e4cb3793-17d5-44be-a129-716d816711c6)

**Comment by dacarson** [comment]
Can you please try `3.3.4-beta.1` and verify that it works.

**Comment by Tomcraft1980** [comment]
After update to the final version 3.3.4 all the misnamed occupancy sensors disappeared.
Is this intentionally?
How can I gett the occupancy sensors back?

**Comment by dacarson** [comment]
It sounds like the same issue as #291 
I am looking into it.

**Comment by dacarson** [comment]
I did cause the sensors to disappear. I fixed them in `3.3.5`.

**Comment by Tomcraft1980** [comment]
Thanks!
Can you publish it to npmjs.com so that we cann update the plugin?

**Comment by dacarson** [comment]
@naofireblade can you help with publishing?

**Comment by naofireblade** [comment]
Done

**Comment by Tomcraft1980** [comment]
Thanks!

**Comment by dacarson** [comment]
Closing as it sounds like it is fixed
