### ISSUE TITLE
Error reading station

### ISSUE THREAD

**Issue by white8398** [naofireblade/homebridge-weather-plus#248]
WeatherUnderground:
[homebridge-weather-plus] Error retrieving weather report and forecast

#Error message: type error: cannot read properties of undefined (reading 'notify')

Any idea how to resolve this issue? I have entered my station id and api key

**Comment by white8398** [comment]
{
            "units": "us",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "Home_outside",
                    "service": "weatherunderground",
                    "key": "2e80e46a30654ec380e46a30655ec3ef",
                    "stationId": "KINWALDR6",
                    "language": "en",
                    "compatibility": "both",
                    "conditionCategory": "detailed",
                    "now": true,
                    "extraHumidity": false,
                    "hidden": [
                        "Cloud Cover",
                        "Humidity",
                        "Solar Radiation",
                        "Temperature Apparent"
                    ],
                    "tresholdAirPressure": 1200,
                    "tresholdWindSpeed": 15
                },

**Comment by mikkyo9** [comment]
I get the same issue.

**Comment by yvbl7544** [comment]
I have exactly the same issue. Any ideas how to solve it?

**Comment by dacarson** [comment]
Dup of #238

**Comment by dacarson** [comment]
Can you please try `3.3.4-beta.1` and verify that it works.

**Comment by dacarson** [comment]
I believe this is fixed. Closing
