### ISSUE TITLE
Wunderground issue not displaying data in HomeKit/eve

### ISSUE THREAD

**Issue by Wirepower** [naofireblade/homebridge-weather-plus#249]
So a connection is made, but no data is being showed. HomeKit displays 8 accessories but showing 0 as a result

**Comment by Mortifer557** [comment]
I have the same issue. I have everything updated to the latest version

**Comment by yvbl7544** [comment]
Same issue with me

**Comment by bondskin** [comment]
same here

**Comment by dacarson** [comment]
If this is still an issue, can someone please add logs

**Comment by dacarson** [comment]
Can you please try `3.3.4-beta.1` and verify that it works now.

**Comment by dacarson** [comment]
I believe this is fixed. Try `3.3.4` or later.
