### ISSUE TITLE
Error Retrieving Weather report

### ISSUE THREAD

**Issue by rlhead** [naofireblade/homebridge-weather-plus#252]
Brand new install of Weather Plus on HOOBS.

keep getting these two errors:
WeatherPlus ERROR Error retrieving weather report
WeatherPlus ERROR [object Object]

I've tried multiple different configs (and API keys at OpenWeather) and locations, and get the same error.

**Comment by davidjbradshaw** [comment]
I’d suggest switching to HomeBridge, I wasted a couple of days with Hoobs, before working out the issues were Hoobs. Switched to HomeBridge, which now has a much nicer UI and everything worked straight away.

**Comment by mtressl** [comment]
Same error here, but running on Homebridge.
`Error retrieving weather report`

Plugin is running in a child bridge but besides this error seems to run fine.

**Comment by mtressl** [comment]
> Same error here, but running on Homebridge. `Error retrieving weather report`
> 
> Plugin is running in a child bridge but besides this error seems to run fine.

But there is no data retrieved.
This is the error I receive:
`Error retrieving weather report
undefined
{
  cod: 401,
  message: 'Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info.'
}`

**Comment by mtressl** [comment]
What I figured out:

- **new API key** does not solve the problem
- **previous plugin version with new API** key results in error as well
- **previous plugin version with old API key** works

@naofireblade - can you check the latest changes introduced and why it uses One Call 3.0?

**Comment by petykowski** [comment]
> > Same error here, but running on Homebridge. `Error retrieving weather report`
> > Plugin is running in a child bridge but besides this error seems to run fine.
> 
> But there is no data retrieved. This is the error I receive: `Error retrieving weather report undefined { cod: 401, message: 'Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info.' }`

I experienced this issue after upgrading to **v3.2.7** this morning. The plug-in is configured to use OpenWeatherMap. I was able to resolve the issue by rolling back to **v3.2.6** and using the original API key.

**Comment by gazzmanzx6** [comment]
Getting this error as well.

Error retrieving weather report undefined { cod: 401, message: 'Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info.' }

Rolling back to previous version gets it working again.

**Comment by naofireblade** [comment]
After registering for api 3.0 and generating a new api key it took about 10minutes for the new api key to be accepted for me.
I will add a configuration variable for switching between old and new api.

**Comment by naofireblade** [comment]
Fixed in v3.2.8

**Comment by korskantevin** [comment]
v3.2.11
