### ISSUE TITLE
Error retrieving weather from OpenWeatherMap after upgrade

### ISSUE THREAD

**Issue by thefern69** [naofireblade/homebridge-weather-plus#254]
I just updated the plug in from the previous version and get this error on startup:

```
[12/29/2022, 3:55:52 PM] [WeatherPlus] Could not retreive weather report with API 3.0, trying API 2.5 now ...
[12/29/2022, 3:55:53 PM] [WeatherPlus] [
  [
    {
      dt: 1672336800,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2022-12-29 18:00:00'
    },
    {
      dt: 1672347600,
      main: [Object],
      weather: [Array],
      clouds: [Object],
      wind: [Object],
      visibility: 10000,
      pop: 0,
      sys: [Object],
      dt_txt: '2022-12-29 21:00:00'
    },
    {
      dt: 1672358400,
      main: [Object],
      weather: [Array],
...
```

it goes on for multiple lines. I haven't changed anything else. I did recheck my API key which is fine.

**Comment by naofireblade** [comment]
Is in an error (red)? Or debug information?
Does youths weather shows correct in HomeKit?

**Comment by thefern69** [comment]
Yea, what looks like JSON is in red and erroring. 

It is in HomeKit but cannot tell if it is correct.

**Comment by naofireblade** [comment]
First line should be white (info) and json should be yellow/orange (warn). That warn log shouldn't have been in the code, my bad. Will update later today.
