### ISSUE TITLE
weewx problem

### ISSUE THREAD

**Issue by msman0** [naofireblade/homebridge-weather-plus#257]
Hi, I have tried to activate it with my weewx station. After starting homebridge I get these error message:

[WeatherPlus] Error parsing weather report for Weewx
[WeatherPlus] Error Message: TypeError: Cannot read properties of undefined (reading '0')

my configuration:

{
            "units": "metric",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "F",
                    "service": "weewx",
                    "key": "http://192.168.99.5/weewx/weewx.json",
                    "locationCity": "V.4.9.1",
                    "language": "de",
                    "compatibility": "home",
                    "conditionCategory": "simple",
                    "now": true,
                    "extraHumidity": false
                }
            ],
            "platform": "WeatherPlus"
        }

The JSON file is displayed correct when I open the URL.

With weather underground it work.

Where is the error that it don't work wie weewx?

Thank you.
Regards.

**Comment by sinabuddy** [comment]
Hi msman0

I solved / found today a problem or error in my installation. 
My homebridge protocol showed everytime a "SyntaxError in Json at position 302" > no values were displayed.

In my "weewx.json" i found this entry:
"uv": 0,0,

My json file makes with this uv value the problem.
So i change "uv": 0,0, (with comma between 0,0 !!) to
"uv: 0.0" (with dot between 0.0)

And now it's running.
For the automatic creation in weewx, i remove the lines with uv in the "simple_weewx.json.tmpl" (my workaround, not the solutions)

maybe it will help you...

**Comment by dacarson** [comment]
Unfortunately, I don't have a weewx with, but it sounds like it is working now. 
I'll close this issue.
