### ISSUE TITLE
openweathermap set to metric only

### ISSUE THREAD

**Issue by selfagency** [naofireblade/homebridge-weather-plus#259]
The `queryUri` in the `getWeatherData` method in [`/apis/openweathermap.js`](https://github.com/naofireblade/homebridge-weather-plus/blob/master/apis/openweathermap.js) explicitly sets the `units` field as `metric`, and the constructor itself doesn't even seem to offer `units` as a parameter. 

```
		const queryUri = url + "?units=metric&lang=" + this.language + "&lat=" + this.locationGeo[0] + "&lon=" + this.locationGeo[1] + "&appid=" + this.apiKey;
```

**Comment by dacarson** [comment]
A couple of points here:
* I haven't tried telling this plugin to use a different unit than metric
* I do know that HomeKit internally only uses metric values and it leaves it up to the clients to convert to units that are configured via platform settings or app settings.
* This plugin seems to assume that all values provided by data providers (eg OpenWeatherMap) are metric
* If the user has configured via this plugin's settings to use different units, then it converts all values to those units just before providing it the Homebridge. Conversion convenience functions are in util/characteristics.js

So, IMO, the above mentioned code is correct.

**Comment by dacarson** [comment]
Closing this as resolved.
