### ISSUE TITLE
[homebridge-weather-plus] Could not retreive weather report with API 3.0, trying API 2.5 now ...

### ISSUE THREAD

**Issue by maisun** [naofireblade/homebridge-weather-plus#263]
Hi, I encountered the error below in HomeBridge, and I have double checked API key which look correct to me.

[homebridge-weather-plus] Could not retreive weather report with API 3.0, trying API 2.5 now ...

Maybe openweathermap changed their API recently? Anybody else experience the same?

**Comment by HomebridgeX** [comment]
The same with me.

**Comment by AdeTheux** [comment]
Same issue here

**Comment by websenat** [comment]
Same issue here

**Comment by cracklincrotch** [comment]
You need to subscribe to the One Call API to get the 3.0 access.

The first 1000 calls to openwethermap per day are free.  You can limit the daily accesses to 1000 to prevent being charged at all.

Once your account has. been updated to the 3.0 subscription, again free if you limit the daily accesses, you won't see that message in the logs anymore.

**Comment by dacarson** [comment]
A log line of:
`[homebridge-weather-plus] Could not retreive weather report with API 3.0, trying API 2.5 now ...`
is ok. It means that it failed to fetch your data from 3.0 API, and is falling back to the legacy 2.5 API - which does work.

I am told that it is free to upgrade to 3.0 API. See this [comment](https://github.com/naofireblade/homebridge-weather-plus/issues/282#issuecomment-1944708432) as well as comment above by @cracklincrotch 

Closing this issue as behaves correctly.
