### ISSUE TITLE
UV index is always 0

### ISSUE THREAD

**Issue by HomebridgeX** [naofireblade/homebridge-weather-plus#264]
Hello,
I use OpenWeatherMap and my UV index is always 0, although the weather station provides a correct value.
I use the Eve (with grouping) compatibility.

Thanks

**Comment by janni2607** [comment]
I have the same problem

**Comment by dacarson** [comment]
Are there any logs produced? 

Looking at the code, it seems that UVIndex and DewPoint are handled specially. So is DewPoint also an issue?

**Comment by janni2607** [comment]
Yes, the dew point always shows -50 degrees C.

**Comment by jkreileder** [comment]
See https://github.com/naofireblade/homebridge-weather-plus/issues/274#issuecomment-1898786420

**Comment by dacarson** [comment]
Active work on this issue is in #274, 
Duplicate of #274

**Comment by dacarson** [comment]
Closing as a duplicate of #274 
This report is older, however, active discussion is happening in #274
