### ISSUE TITLE
Sharing Wind Speed Hack

### ISSUE THREAD

**Issue by RCdiy** [naofireblade/homebridge-weather-plus#265]
Especially useful for multiple actions at different wind speed. 
![image](https://github.com/naofireblade/homebridge-weather-plus/assets/20209851/4000c039-c9d2-4002-9326-c851819fede6)

My way of reading the wind speed. 

Plugin used to create a light accessory homebridge-http-webhooks

![image](https://github.com/naofireblade/homebridge-weather-plus/assets/20209851/0c9a8830-0bcc-48d1-8682-77251f22b4d0)

**Comment by AdeTheux** [comment]
Could you explain a bit more please, or share the shortcut?
Not sure I understand the logic with the IP address. Is that your HB url:port?
Thanks
