### ISSUE TITLE
Each sensor is named "Now"

### ISSUE THREAD

**Issue by Tobiwan141** [naofireblade/homebridge-weather-plus#268]
Hi there,

I have the following issue, every sensor is named after "nameNow": "**_Now_**", if I delete the name in the dedicated sensor, I can see which sensor is behind. I can change the name, but the values for e.g. Wind Speed is not shown. 

Furthermore, all sensors are "greyed". 

Maybe it´s a config issue, but I cannot finde the root cause.

Thanks in advance!

    "platform": "WeatherPlus",
    "service": "openweathermap",
    "key": "blablabla",
    "locationGeo": [
        xx.xxxxx,
        y.yyyyy
    ],
    "compatibility": "both",
    "conditionCategory": "detailed",
    "hidden": [],
    "interval": 5,
    "language": "en",
    "nameNow": "**_Now_**",
    "nameForecast": "Blabla forecast",
    "now": true,
    "extraHumidity": true,
    "units": "metrics"

**Comment by dacarson** [comment]
Can you post a screen shot of what you are seeing?

**Comment by zelik888** [comment]
Exactly the same issue.  I believe this is ios17 related

**Comment by ggiese2000** [comment]
Very similar situation here: had to reinstall plugins after major hombridge update.
Now all occupancy sensors are called "Anwesenheitssensor X" with x being a number, in fact there are 2 of each - one for NOW, one for forecast.

**Comment by dacarson** [comment]
This sounds like it is the same issue as reported in #247

**Comment by dacarson** [comment]
Duplicate of #247

**Comment by zelik888** [comment]
Appears fixed! Of course I can't test the NOW sensors but forecast works and names aren't the same. This is great, thank you.

**Comment by dacarson** [comment]
Closing as fixed, in 3.3.4
