### ISSUE TITLE
OpenWeatherMap nor forcast devices, data available in Browser

### ISSUE THREAD

**Issue by WRTHacker** [naofireblade/homebridge-weather-plus#270]
Hello,
I get no forecast infos in HomeKit in any App. The "now" data ist available. I double check an create a second bridge to test around. There al also no device in homebridge ... nothing at all. Both bridges are paired, an shown e.g. in Controller for homekit:

Config:

{
            "units": "si",
            "interval": 15,
            "stations": [
                {
                    "displayName": "C-Lemgo",
                    "service": "openweathermap",
                    "key": "api-key",
                    "locationGeo": [
                        52.0,
                        8.7
                    ],
                    "locationCity": "Lemgo, DE",
                    "language": "de",
                    "compatibility": "eve",
                    "forecast": [
                        "1",
                        "2",
                        "3",
                        "4"
                    ],
                    "nameForecast": "C-LE OWM Vorhersage",
                    "conditionCategory": "detailed",
                    "now": false,
                    "extraHumidity": false
                }
            ],
            "platform": "WeatherPlus",
            "_bridge": {
                "username": "1E:04:9A:2B:AB:3F",
                "port": 38573
            }

Output when child bridge is restarted:

[8/11/2023, 4:48:00 PM] [homebridge-weather-plus] Adding station with weather service OpenWeatherMap named 'C-Lemgo'

The other bridge with the "now" data of weatherunderground an openweathermap works. Putting the config togeather in one bridge changes nothing.

I have absolute no idea and any help is appreciated.

Best regards

**Comment by dacarson** [comment]
Confirming that you do have an actual API Key entered? 
I assume that the configuration file you pasted above was modified and you removed the API Key here:
`"key": "api-key",`

**Comment by WRTHacker** [comment]
Yes ists the identical key entered for the other bridge, which ist working with "now" weather correctly.

**Comment by WRTHacker** [comment]
Ok. Solution:
- Delete Bridge from Homekit
- Delete Plugin
- Setup everything from scratch
- Add to Homekit

Works like expected

Not really nice, cause I had to setup several automations from scratch.
Perhaps the update path of the plugin and the historical data couse this issue.
