### ISSUE TITLE
Add Light Level history/graphing support

### ISSUE THREAD

**Issue by dacarson** [naofireblade/homebridge-weather-plus#287]
With this PR now merged to fakegato [Added lux to accessoryType 'custom'](https://github.com/simont77/fakegato-history/pull/128) , this plugin should be able to support Light Level history in the Eve app.

**Comment by dacarson** [comment]
I have made this work with two changes:
1. Add the logging to `index.js:277`
`lux: accessory.LightLevelService ? accessory.LightLevelService.getCharacteristic(Characteristic.CurrentAmbientLightLevel).value : accessory.CurrentConditionsService.getCharacteristic(Characteristic.CurrentAmbientLightLevel).value`

2. Switch from 'weather' to 'custom', in `currentConditions.js:151`  but also do this:
```
	this.services = [this.CurrentConditionsService];
	this.historyService = new FakeGatoHistoryService("custom", this, this.config.fakegatoParameters);
	this.services = this.getServices();
```

The 2nd part doesn't seem right. When examining the code in [FakeGato](https://github.com/simont77/fakegato-history/blob/6276b6ef17b5ec6688f43abbdfc61d0b1dbb5f5e/fakegato-history.js#L325), it looks at all the `Services` that are part of the `Accessory`. And then for each `Characteristic` of each `Services` it checks to see if it can create a history entry for it. If so, it does.

The challenge is the `historyService` **is part of** the `Accessory` and if I don't override the value of `this.service` it crashes. It crashes because when it walks the list of Services, it reaches the historyService which is `undefined` at that moment.

I'm wondering if there is different way `Services` should be registered with the `Accessory`.

**Comment by dacarson** [comment]
This is what it currently looks like:
![IMG_4935](https://github.com/naofireblade/homebridge-weather-plus/assets/44933987/34c214c3-ed70-4b5f-be27-b43ddcd92a0d)

**Comment by dacarson** [comment]
Worked out an elegant fix. Following the pattern in `index.js` that has an array of Accessories:
`this.accessoriesList = [];`

In `currentConditions.js`, create an array of services, aka `this.services = [];`
Then add each Service as they are created, aka:
`this.services.push(this.CurrentConditionsService);`
later
`this.services.concat(compatibility.getServices(this));`
and later:
`this.services.push(this.informationService);`
and lastly do this:
```
	this.historyService = new FakeGatoHistoryService("custom", this, this.config.fakegatoParameters);
	this.services.push(this.historyService);
```

Change `getServices()` function to just return the services object:
```
	getServices: function ()
	{
		return this.services;
	}
```

This way, only fully defined `Service` objects exist in the services array. `FakeGatoHistoryService` is now happy.

**Comment by wimleers** [comment]
Very interesting!
