### ISSUE TITLE
Unable to uninstall or update

### ISSUE THREAD

**Issue by HGordonH** [naofireblade/homebridge-weather-plus#289]
Hi,

This plugin broke for me some time ago. Ive been unable to update or uninstall

This is the error

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/homebridge-weather-plus
npm ERR! dest /usr/lib/node_modules/.homebridge-weather-plus-RCH9Us1A
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/homebridge-weather-plus' -> '/usr/lib/node_modules/.homebridge-weather-plus-RCH9Us1A'

npm ERR! A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-02-22T16_10_50_740Z-debug-0.log

**Comment by dacarson** [comment]
I am not sure where the '/usr/lib/node_modules/.<plugin-name>-<RANDOM-CHARACTERS>' files come from. Some of my plugins have them and others don't. In my case, I actually don't have a '/usr/lib/node_modules/.homebridge-weather-plus-<RANDOM-CHARACTERS>' on my file system. 

I would post this issue to the HomeBridge as I don't believe that it is anything this plugin is doing.
