### ISSUE TITLE
Weather Underground no longer offering free API access

### ISSUE THREAD

**Issue by molgar** [naofireblade/homebridge-weather-plus#29]
It seems it is now impossible to get a free API key.

**Comment by naofireblade** [comment]
Oh thats disappointing. I will change the plugin to use another service then.

**Comment by calanish** [comment]
The OpenSprinkler project has moved to using https://www.pwsweather.com/ .

**Comment by Nastras** [comment]
@naofireblade 

For me the existing API does not work anymore since today. I wanted to ask when you change the service for your plugin? Would not like to use another plugin.

Greeting Nastra

**Comment by Nastras** [comment]
Have found the error, it seems as if the Pwd designations of some weather station had changed. I've changed this in the config now on a current station now it works again.

The problem was not the existing API.

**Comment by calanish** [comment]
OpenSprinkler is using OpenWeatherMap  - not PWS

If there is no API key in the config it defaults at the server to send data from OWM rather than WU.

BTW I am just an OpenSprinkler user, if you want more detail then opensprinkler.net is the place to go.

**Comment by naofireblade** [comment]
I currently consider adding OpenWeatherMap (supports pws) and/or Dark Sky (more features but no pws support and latitude+longitude required). Does anybody have more recommendations?

**Comment by RGSMA** [comment]
My WU API is still working but I'm wondering for how much longer. Your plugin is very important to my homebridge setup. Have you given any more thought to a replacement for WU if it becomes necessary?

**Comment by naofireblade** [comment]
I'm reworking the plugin to support multiple apis. I will give a table that compares the features of each api in the readme.

**Comment by naofireblade** [comment]
Rework is done with (version 2.0.0)[https://www.npmjs.com/package/homebridge-weather-plus]
