### ISSUE TITLE
No wind sensor with 3.3.4 Beta 1

### ISSUE THREAD

**Issue by threeonparfive** [naofireblade/homebridge-weather-plus#291]
I recently had a problem where the UI bug in 3.3.3 fails to show the wind speed threshold and apparently also causes it's removal from the JSON config if you modify a setting after initial setup, like the polling interval.  This is with Weatherbug and a PWS.  Because I wasn't sure where the wind speed setting was supposed to go in the JSON config, I opted to try the 3.3.4 Beta 1 since it's specifically documented to fix this UI bug.  It did do that but no wind speed occupancy sensor is created at all when running the beta, though the wind speed threshold is in the config.  As soon as I roll back to 3.3.3, the wind speed sensor shows up.

**Comment by dacarson** [comment]
Can you share a copy of your configuration?

**Comment by threeonparfive** [comment]
[
	{
		"_bridge": {
			"username": "00000000",
			"port": 59142
		},
		"platform": "WeatherPlus",
		"units": "us",
		"stations": [
			{
				"language": "en",
				"nameNow": "KPTPeppertree",
				"thresholdWindSpeed": 6,
				"conditionCategory": "simple",
				"key": “xxxxxxxxx",
				"extraHumidity": false,
				"now": true,
				"compatibility": "home",
				"hidden": [
					"Air Pressure",
					"Cloud Cover",
					"Condition",
					"Condition Category",
					"Dew Point",
					"Forecast Day",
					"Humidity",
					"Observation Station",
					"Observation Time",
					"Ozone",
					"Rain",
					"Rain 1h",
					"Rain Day",
					"Rain Chance",
					"Snow",
					"Solar Radiation",
					"Sunrise Time",
					"Sunset Time",
					"Temperature Min",
					"Temperature Apparent",
					"UV Index",
					"Visibility",
					"Wind Direction",
					"Wind Speed Max"
				],
				"stationId": "KTNKINGS343",
				"service": "weatherunderground"
			}
		],
		"interval": 1
	}
]

**Comment by dacarson** [comment]
Thanks. 
In the code, I see it setting the value. But you are right, it doesn't appear in the app.

**Comment by threeonparfive** [comment]
I noticed 3.3.4 code is now released.  Does it include a fix for this issue seen in beta or still a work in progress?  Wasn't sure if I should be upgrading yet or not.  Thanks!

**Comment by naofireblade** [comment]
I missed this ticket. I released the 3.3.4 beta as final because it solved a lot of bugs. This issue is not fixed in 3.3.4.

**Comment by naofireblade** [comment]
I removed the 3.3.4 release from npm for now.

**Comment by dacarson** [comment]
I am testing your stationId with my API key, and my API key has just started returning 401, Not Authorized. Though WUnderground site still says that my API key is valid. I have reached out to their support department to understand more.

**Comment by dacarson** [comment]
I have found the issue, but I don't understand why it's an issue.
<img width="1176" alt="Diff" src="https://github.com/naofireblade/homebridge-weather-plus/assets/44933987/86327ee6-5f70-421f-88ab-fbe6514a40fe">

**Comment by dacarson** [comment]
Understand why the original code doesn't work.
I need to have:
`this.services = this.services.concat(compatibility.getServices(this));`
as concat() doesn't modify the original array., it returns a new array with both sets of elements.

**Comment by threeonparfive** [comment]
Great!!  I’ll be on the lookout for an update.  Thanks for the quick fix!

**Comment by threeonparfive** [comment]
When should this code release appear in Homebridge? Thanks!

**Comment by dacarson** [comment]
I can't publish this repo. I need @naofireblade to publish it.
