### ISSUE TITLE
Windspeed and Windspeed Gust bad values in Weather Underground

### ISSUE THREAD

**Issue by angladacamps** [naofireblade/homebridge-weather-plus#299]
I'm pretty sure that the plugin is somewhat reporting bad wind speed / gusts in Weather Underground. For example, I have today a max gust of 35 Km/h and plugin says, in Eve App, 104Km/h. Has anyone noticed this issue?

**Comment by threeonparfive** [comment]
Already reported and being worked on here: [Issue #296](https://github.com/naofireblade/homebridge-weather-plus/issues/296)

**Comment by dacarson** [comment]
Yes, duplicate of 296.
Closing as a duplicate
