### ISSUE TITLE
Cannot get plugin to start without errors

### ISSUE THREAD

**Issue by ikonis** [naofireblade/homebridge-weather-plus#35]
Here's my json for the plugin. Removing it from my config, then homebridge loads fine.
      {
        "platform": "WeatherPlus",
        "name": "Weather",
        "service": "darksky",
        "key": "xxxxxxxxxxxxxxxxx",
        "location": [##, -##],
        "language": "en",
        "forecast": [1]
      }

and of course, when loading the platform i get this error

> Aug 22 11:18:54 raspberrypi homebridge[3612]: [2018-8-22 11:18:54] [homebridge-plex-sensors.Plex] Initializing homebridge-plex-sensors.Plex platform...
>Aug 22 11:18:54 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
>Aug 22 11:18:54 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
>Aug 22 11:18:54 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
>Aug 22 11:19:04 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.

Weather-Plus being the next platform to load.

**Comment by werthdavid** [comment]
Can you start homebridge with debug-option and provide the log output? See [here](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting) basically just start homebridge with "-D"

**Comment by daveramirez5** [comment]
I was having a very similar issue and the problem is that I mistakenly put the platform in the accesories section on the config json. Check if is not happening to you too.
