### ISSUE TITLE
Update to 2.0.4 interrupts

### ISSUE THREAD

**Issue by brandungskieker** [naofireblade/homebridge-weather-plus#40]
Trying to update weather-plus but the update interrupts on step

`extract:node-forge: sill extract node-forge@^0.7.1 extra`

The npm process won't proceed. Latest Homebridge, Node v8.9.4. Any ideas?

**Comment by naofireblade** [comment]
Iit also hangs a while at that step for me but finally continues after some minutes (approx. 5).
