### ISSUE TITLE
Ability to show humidity as a tile in Home/Eve

### ISSUE THREAD

**Issue by kimme1024** [naofireblade/homebridge-weather-plus#41]
I just switched from homebridge-openweathermap to this plugin as this one has a lot more data available and is also greatly integrated with the Eve app!
Great work on that!

The 1 thing that I miss from openweathermap is the ability to show the humidity on a tile in favorites.

Is there a way to do this myself or does it have to be implemented in the code?

I hope this will become available in future versions!

Keep up the great work!

**Comment by werthdavid** [comment]
Currently not implemented. You could use both plugins at the same time or open a PR 😄

**Comment by dVIAN13** [comment]
+1, Interested in this functionality as well! great work on the project! maybe an additional value for 'currentObservations' that breaks out relative humidity into it's own object..

**Comment by apexad** [comment]
Interested in this as well.  May attempt to add it when I have some free time, but if anyone else has time, I am totally ok with you beating me to it!

**Comment by naofireblade** [comment]
I'm working on this for the next release.

**Comment by naofireblade** [comment]
Added in v3.0.0 (not yet released).

**Comment by naofireblade** [comment]
Alright, this is added in v3.0.0-beta.1
You can test the beta with `npm install -g homebridge-neato@beta`

**Comment by naofireblade** [comment]
Thanks for the log and config. I fixed it in version 3.0.0-beta.2

You also need to add this to the config to make humidity an extra tile `"extraHumidity" = true,`

**Comment by apexad** [comment]
Working great!

**Comment by kimme1024** [comment]
Hi!

Great to see my request being added! Thanks for that!
However I seem to have an issue adding the extraHumidity part.

When adding "extraHumidity": "true", I'm getting following error when starting homebridge:

[2019-12-8 14:36:15] [WeatherPlus] Exception while parsing weather forecast: TypeError: Cannot read property 'setCharacteristic' of undefined
[2019-12-8 14:36:15] [WeatherPlus] Forecast: undefined
[2019-12-8 14:36:15] [WeatherPlus] Exception while parsing weather forecast: TypeError: Cannot read property 'setCharacteristic' of undefined
[2019-12-8 14:36:15] [WeatherPlus] Forecast: undefined
[2019-12-8 14:36:15] [WeatherPlus] Exception while parsing weather forecast: TypeError: Cannot read property 'setCharacteristic' of undefined
[2019-12-8 14:36:15] [WeatherPlus] Forecast: undefined
[2019-12-8 14:36:15] [WeatherPlus] Exception while parsing weather forecast: TypeError: Cannot read property 'setCharacteristic' of undefined
[2019-12-8 14:36:15] [WeatherPlus] Forecast: undefined
[2019-12-8 14:36:15] [WeatherPlus] Exception while parsing weather forecast: TypeError: Cannot read property 'setCharacteristic' of undefined
[2019-12-8 14:36:15] [WeatherPlus] Forecast: undefined

I checked previous posts and you mention using "extraHumidity" = true, but this triggers a syntax error as it's not a correct layout for the json file.

How should I add the feature correctly?

Thanks in advance!

**Comment by tooh** [comment]
@kimme1024  I assume you used syntax "extraHumidity": true ?

**Comment by kimme1024** [comment]
> @kimme1024 I assume you used syntax "extraHumidity": true ?

First I've used:

"extraHumidity": "true",

as this was in line with the other ones

now I just tried

"extraHumidity":true

Sadly with the same results.

**Comment by tooh** [comment]
Added "extraHumidity": true and get extra Humidity but can conform that my 2 day forecast is gone.

**Comment by kimme1024** [comment]
> plugin version v3.0.4
> 
> Added "extraHumidity": true and get extra Humidity but can conform that my 2 day forecast is gone.
> `[WeatherPlus] Exception while parsing weather forecast: TypeError: Cannot read property 'setCharacteristic' of undefined`

same issue here

**Comment by naofireblade** [comment]
@tooh @kimme1024 could u provide your config please?

**Comment by kimme1024** [comment]
I just removed the forecast for now.

```
        {
            "platform": "WeatherPlus",
            "service": "darksky",
            "compatibility": "eve",
            "extraHumidity": true,
            "key": "73dfa0c8f54d7d5d5233d477625b7107",
            "locationGeo": [
                50.947881,
                4.60274
            ],
            "interval": "5",
            "displayName": "Temperature",
            "language": "en"
        },
```

**Comment by naofireblade** [comment]
I just added a forecast to your config and its working for me. Could you check I u still experience problems with the latest version 3.1.1 please?

```
        {
            "platform": "WeatherPlus",
            "service": "darksky",
            "compatibility": "eve",
            "extraHumidity": true,
            "key": "xxx",
            "locationGeo": [
                50.947881,
                4.60274
            ],
            "interval": "5",
            "displayName": "Temperature",
            "language": "en",
            "forecast": [0,1,2]
        }
```

**Comment by naofireblade** [comment]
I think the issue no longer exists. I will close this until new information is provided.
