### ISSUE TITLE
Some texts are not translated

### ISSUE THREAD

**Issue by carsten-h** [naofireblade/homebridge-weather-plus#42]
I choose to let me display the results of "Dark Sky" in the language "de".
But inside the Eve App I still can see eg. the texts "Now", "Today" or "In x days". Also some texts of the measured values like "Ozone" are still in English.

Is it not possible to get them also translated?

Best Regards!
Carsten

**Comment by werthdavid** [comment]
Well... the language parameter acutally only tells the API to return the values in the specified language. The plugin itself does not directly translate anything, that's why the mentioned texts are still in english..
Would be a good enhancement for sure!

**Comment by carsten-h** [comment]
Good morning!

 

So where will be the place to translate the missing texts? Can I help anywhere?

 

Best Regards!

Carsten

 

Well... the language parameter acutally only tells the API to return the values in the specified language. The plugin itself does not directly translate anything, that's why the mentioned texts are still in english..
Would be a good enhancement for sure!

**Comment by naofireblade** [comment]
I will rework some parts so that language files are supported. I will post an update here when it's ready.

**Comment by carsten-h** [comment]
Thank you very much!

**Comment by naofireblade** [comment]
Language files for day translations will be added in v3.0.0
