### ISSUE TITLE
Eve Weather emulation

### ISSUE THREAD

**Issue by simont77** [naofireblade/homebridge-weather-plus#44]
Hi naofireblade,
as you know some time ago I forked your plugin for using it as a test bench for fakegato. Now you greatly evolved it, with API for services different from the original Wunderground. Now that Wunderground will probably shutdown free API access, I would like to move myself to your new version, but I would still prefer to emulate Eve Weather, with its custom service rather than the standard temperature service, so I would implement some modifications. Would you be interested in such an option for your plugin? If so, I would add this feature as an optional parameter and issue a pull request.
Let me know.

**Comment by naofireblade** [comment]
Hey simont77,
thank you for your message. That would be awesome! I really appreciate your work for the fakegato library (you are already listed as a contributor in the readme :) and would love to have you working on the homebridge-weather-plus plugin.
Just submit your pull request at any time and I will merge and release it asap.

**Comment by simont77** [comment]
Ok, give me some time to work on that and test it.
