### ISSUE TITLE
New Yahoo API

### ISSUE THREAD

**Issue by simont77** [naofireblade/homebridge-weather-plus#45]
Hi, 
are you aware of this advise from Yahoo?

“Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. 
To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Contact yahoo-weather-ydn-api@oath.com for credentials to onboard to this free Yahoo Weather API service.”

First Wunderground, now Yahoo, It seems more and more difficult to get access to free weather APIs...

**Comment by naofireblade** [comment]
I tried to create an app there but got an internal error. I mailed them now and requested a key. Let's see what happens.

**Comment by dacarson** [comment]
Yahoo no longer has a weather API. I think we should just remove it.
You can sign up for free weather from OpenWeather.

**Comment by dacarson** [comment]
Yahoo has been removed. 

No plans on adding it back.
