### ISSUE TITLE
Weathercloud as a Service

### ISSUE THREAD

**Issue by djnav** [naofireblade/homebridge-weather-plus#59]
hey there

with the demise of weather underground allowing pws to be easily used via there api, wondering if Weathercloud will be able to be added as a service for this Homebridge plugin, have been using this service for over a year now with great reliability.

https://weathercloud.net

not sure how involved tis will be to implement into this plugin, but appreciate the work you do for us to be able to utilise this plugin

Cheers

**Comment by naofireblade** [comment]
I don't see any hints of an api for weathercloud. I guess they don't offer api access.

**Comment by djnav** [comment]
I have had my pws uploading to Weathercloud for over a year now no issues.

https://app.weathercloud.net/d0305065326#profile

when setting up my pws I used the app WS Tools and it asked to about weather cloud and gave me a id key to register create account online and pws started uploading data

hasn't missed a beat apart from when my net is down, and it'll send me an email letting me know device is offline too

devices supported: https://weathercloud.net/info/compatibility

**Comment by dacarson** [comment]
We should close this issue. Unfortunately WeatherCloud does not offer an API:
https://weathercloud.net/en/faq#faq-api_data_retrieval

**Comment by dacarson** [comment]
@naofireblade please close this issue.

**Comment by MauroDruwel** [comment]
Well there is one, it's just not official/documented. The website makes API calls and someone already reverse-engineered it for js. https://github.com/maxime-mrl/weathercloud-js
Auth isn't even needed
