### ISSUE TITLE
Weather Condition Category incorrect

### ISSUE THREAD

**Issue by misanthrophy** [naofireblade/homebridge-weather-plus#60]
Hi,

I installed your plugin to make some automations with the telegram Plugin etc.

According to your README file you configured the plugin like this:

Condition Category (Sun = 0, Clouds = 1, Rain = 2, Snow = 3)

I then checked in the controller App to use 0, 1, 2, 3 as a condition but there it shows me for 0: Bewoelkt, 1 for Nebel, ...

So something is not correct here... 

If I can not properly choose the condition category numbers, do you know if there is a way to use your sentence for Weather Condition in Telegram? So that it checks your sentence and copies it into a telegram notification? 

Thx in advance!

**Comment by naofireblade** [comment]
Hey, which weather service do you use?

**Comment by misanthrophy** [comment]
I am using the Dark Sky Weather Service.

Today for example it should rain in Berlin 92%. Weather Condition says Überwiegend bewölkt bis Abends. And Weather Condition Category is set to 0.

**Comment by misanthrophy** [comment]
![12D72578-B84E-4934-9065-E6BAFEF67E6E](https://user-images.githubusercontent.com/22965340/56881727-a559ab80-6a61-11e9-8ce4-3e9b2aa28e18.png)
The Now section seems correct with category 2 and Nieselregen. But on all the other days, it does not update the category!

**Comment by naofireblade** [comment]
Will be fixed in v3.0.0. The keyword for "Überwiegend bewölkt" in darsky is "partly-cloudy-day". I expected this keyword to imply a overall sunny day. I changed it now to cloudy (1).

**Comment by naofireblade** [comment]
Alright, this is fixed in v3.0.0-beta.1 This version also has an option for more detailed categories.
You can test the beta with `npm install -g homebridge-weather-plus@beta`
