### ISSUE TITLE
enhancement request for new wunderground api

### ISSUE THREAD

**Issue by brandoniske** [naofireblade/homebridge-weather-plus#62]
A new wunderground api for personal weather stations has been released and a new node pkg supporting it exists: https://www.npmjs.com/package/weather-underground-node

Would love to see support for it added to homebridge-weather-plus.

**Comment by naofireblade** [comment]
Thanks for the link. I will look into this.

**Comment by mwkchan** [comment]
I can confirm the current plugin cannot fetch data from the PWS API. Would be great if this can be added. So far the weather plus plugin is the best of its kind.

**Comment by mwkchan** [comment]
Here is a link to the new API documentation: https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit

**Comment by naofireblade** [comment]
Added in v2.8.0
