### ISSUE TITLE
Select only certain observations?

### ISSUE THREAD

**Issue by mikesalz** [naofireblade/homebridge-weather-plus#63]
Hello. Is it possible to select only certain. Particular observations to expose to homekit? For example, I am only interested in wind speed and cloud cover. Can I hide the others?

**Comment by naofireblade** [comment]
Hey, sorry that's currently not possible. I keep this open as an idea for future development.

**Comment by mikesalz** [comment]
Sounds good.  Thanks!

**Comment by mikesalz** [comment]
Also, I forgot to mention... THANK YOU for taking the time to create such a great plugin!

**Comment by naofireblade** [comment]
Added in newest version v3.0.0 (not yet released)

**Comment by naofireblade** [comment]
Alright, this is added in v3.0.0-beta.1
You can test the beta with `npm install -g homebridge-weather-plus@beta`
