### ISSUE TITLE
Interval default

### ISSUE THREAD

**Issue by mensa84** [naofireblade/homebridge-weather-plus#66]
Hello,

shouldn't the default interval be 2 minutes? Cause at Dark Sky free API there are 1000 free calls per day allowed. Or why do you still use 4?
Exactly every 1.44 minute a call should be allowed. Would it work to set the interval to 1.44 minutes?

**Comment by naofireblade** [comment]
4 minutes was an average that works with all currently supported weather services. The free darksky service is awesome. I think it's fair to not request their servers to often.
