### ISSUE TITLE
New Weather Undergroud API

### ISSUE THREAD

**Issue by DSchumacher2104** [naofireblade/homebridge-weather-plus#67]
Hello @naofireblade !

After WU disabled free API-Keys last year, there is a new method to get data from PWS with API-Calls. It would be very nice, if you could add this feature into your plugin so we can use the PWS-feature of WU in HomeKit again. When entering an existing pws as StationID like "IDARMSTA223" and using this API-Call
`https://api.weather.com/v2/pws/observations/current?apiKey=6532d6454b8aa370768e63d6ba5a832e&stationId=StationID&format=json&units=m`

we get a JSON

`{
  "observations": [
    {
    "stationID": "IDARMSTA223",
    "obsTimeUtc": "2019-05-27T08:00:25Z",
    "obsTimeLocal": "2019-05-27 10:00:25",
    "neighborhood": "Tulpenweg",
    "softwareType": "WH2602 V4.5.6",
    "country": "DE",
    "solarRadiation": 159.31,
    "lon": 8.64811707,
    "realtimeFrequency": null,
    "epoch": 1558944025,
    "lat": 49.90708923,
    "uv": 2.0,
    "winddir": 103,
    "humidity": 93,
    "qcStatus": 1,
    "metric": {
      "temp": 15,
      "heatIndex": 15,
      "dewpt": 14,
      "windChill": 15,
      "windSpeed": 0,
      "windGust": 0,
      "pressure": 1008.81,
      "precipRate": 0.0,
      "precipTotal": 1.02,
      "elev": 224
      }
    }
  ]
}`

The API-Key is a public-key and does't change. Sadly, there is no forecast, but we can get local weather data again! Update-intervall shloud be 600 sec.

Thanks for your work!

**Comment by rsonnens** [comment]
I second this request, I'd love for the newer API to be enanabled (I have a public API key that is obviously different than the one above.) 

The weather underground folks gave me this key for the asking and is available to non-legacy users such as myself.

**Comment by mwkchan** [comment]
As I run my own PWS, I am totally supportive on the suggestion!

**Comment by knuckleheadsmiff** [comment]
So I made my own branch that I hooked up to the new API--I kept the old implementation as-is. Only thing that I don't get is how I can see 'custom characteristics' in the home app--or I have some bug? I can only see temperature and humidity.  Which is fine as all I wanted to do was ask siri the temp outside my house. ;-)

Also, while it takes 'units' as a config parameter homekit seems to only understating metric but reports to me in Fahrenheit which is what I want.So I'm nit sure I understand what the units in the config do.

I don't have an EVE or use that app so maybe the stuff shows up there?

I have no plans to ask to ask to merge this back as it is my "first" git project and "npm". Sadly I debugged the old fashion way, could not figure out how to debug the HomeKit plugins in a nodeJS debugger. That would have made things easier. :-(

**Comment by knuckleheadsmiff** [comment]
Whoo, I installed the EVE app and I see the custom characteristics! All look correct. I think I fix pop do doc file tomorrow and request this to be pushed to the main release.

![IMG_2799](https://user-images.githubusercontent.com/54040140/64132383-5bbcfc80-cd84-11e9-83f2-b67e5e603058.png)

**Comment by knuckleheadsmiff** [comment]
Ok Pals! I created a pull request to get this back to the master branch. Since the above post I've removed the old API since it has been offline since March so no need to preserve that old code. That caused me to rename a few files and clean up some cruft. I've also fixed the "observation time'  field. This is the time that weather station data was last pushed to weather underground feed, not the time the data was pulled (unlike the the other plugging which use the time the data was pulled.) 

I also added rain total for the day amounts. I had some more info but I afaik the Eve I push all the info that WU feed gives me that Eve and the Apple Home app understand.

https://github.com/naofireblade/homebridge-weather-plus/pull/72

**Comment by mwkchan** [comment]
Well done!

**Comment by cyberhusky69** [comment]
Great work.
Do I understand this correctly that this plugin is for users with an own weatherstation?

**Comment by knuckleheadsmiff** [comment]
should be able to install from here:

https://github.com/knuckleheadsmiff/homebridge-weather-plus

Doc instructions  has been updated.

The install should just have my name In the path.

sudo npm install -g knuckleheadsmiff/homebridge-weather-plus

**Comment by naofireblade** [comment]
Awesome! I will merge the PR in the next few days.

**Comment by knuckleheadsmiff** [comment]
Naofireblade, need any help with the merge? Let me know if you have issues.

**Comment by naofireblade** [comment]
Thanks for the reminder. I just had no time to look into the code until now. I cannot test it without a device that can post to weather underground but the code looks code. I made some minor changes and submitted the new version.
Thank you very much for your help! Pull Requests are keeping open source projects alive :) .

**Comment by knuckleheadsmiff** [comment]
Thanks, I think the unused callback was left over from probably a first version.

That that/this charge was not really necessary as I did bind “bind” The this object to that function call but you change should not matter. 

I’ll install and test this after noon.

**Comment by knuckleheadsmiff** [comment]
Seem to be working. ;-)

thanks for merging.

**Comment by quim-net** [comment]
Hello, thank you very much, I have managed to follow my pws on eve through hombrigde.

**Comment by quim-net** [comment]
![024AB0DF-CEBD-472B-9D87-B0CEB0AB72AE](https://user-images.githubusercontent.com/55294004/64925827-79637a80-d7f6-11e9-8f34-4790cb2d1102.png)

**Comment by quim-net** [comment]
Hi, 
![D2986A71-6B75-4919-8B25-91B6D211890A](https://user-images.githubusercontent.com/55294004/65049748-93bc6600-d966-11e9-9e4c-0b3fa5d3e5be.jpeg)
![4338B56F-05F4-4CCD-9E2F-ED1CCBDB1500](https://user-images.githubusercontent.com/55294004/65049750-93bc6600-d966-11e9-90d4-3500e41155d0.jpeg)

 in the last update of "eve" shows again the drop-down menu of temperature and other

**Comment by knuckleheadsmiff** [comment]
> Hi,
> ![D2986A71-6B75-4919-8B25-91B6D211890A](https://user-images.githubusercontent.com/55294004/65049748-93bc6600-d966-11e9-9e4c-0b3fa5d3e5be.jpeg)
> ![4338B56F-05F4-4CCD-9E2F-ED1CCBDB1500](https://user-images.githubusercontent.com/55294004/65049750-93bc6600-d966-11e9-90d4-3500e41155d0.jpeg)
> 
> in the last update of "eve" shows again the drop-down menu of temperature and other

Interesting. This historical data is most likely retained in homekits database. I wish Apple’s home app would expose it.

**Comment by naofireblade** [comment]
The data is retained in a json file (also configurable to google cloud drive) of your homebridge installation and queried when the device is opened in eve.
It's a custom eve format and sadly not stored in a homekit database on apple servers.
