### ISSUE TITLE
Error retrieving weather report and forecast for DarkSky

### ISSUE THREAD

**Issue by newmans99** [naofireblade/homebridge-weather-plus#68]
I have the homebridge-weather-plus plugin running in two separate homebridge servers (both in Docker, on separate physical hardware). Their platform configuration is 100% the same (except lat/long) and are using the same apikey. The homebridge server starts up, the plugins load correctly, and the accessories are all initiated. However, every five minutes on the raspberry pi's homebridge weather-plus log files, I get the following errors:

8/6/2019, 10:17:17 PM] [WeatherPlus] Error retrieving weather report and forecast for DarkSky
[8/6/2019, 10:17:17 PM] [WeatherPlus] Error Message: Forecast cannot be retrieved. Response: 500 Internal Server Error

I can not seem to find any debug options to help me debug this issue. Any ideas (or better place to post these questions)?

**Comment by newmans99** [comment]
This resolved itself today and it is working correctly. I don't know what changed so maybe it just needed a bit of a break.

**Comment by naofireblade** [comment]
500 is an error inside the DarkSky server. Maybe they had a problem with the weather for your location.
