### ISSUE TITLE
Eve stops picking up temperature history

### ISSUE THREAD

**Issue by gdotp01** [naofireblade/homebridge-weather-plus#71]
Im running a Pi Zero using Homebridge with this plugin. It generally works but twice in the last 6 months I've found that the Eve App no longer picks up the temperature history from the pi. Last time it happened I messed around a little and it started working again and its done the same today. it is looking at the DarkSky Api as i can see the accesses vid the DarkSky portal. 

Eve is showing the correct temperature and wind speed.

I presume that the data is logged into a file somewhere on the pi but I'm  not sure where  to check if its logging the measurements. 

Any help greatly appreciated

**Comment by tomsteenbakkers** [comment]
+1

**Comment by DeutscheMark** [comment]
+1

**Comment by thebodster** [comment]
This has been caused by a recent update to the eve app.  The fakegato service, that this relies upon, no longer works.  https://github.com/simont77/fakegato-history/issues/76

**Comment by simont77** [comment]
Actually, fakegato still works, but Eve is more strict on Characteristics exposed by accessories. The Eve mode of homebridge-weather-plus (i.e. combined temperature, humidity and pressure usable only with Eve.app) still works. The default mode with separate sensors need some change in homebridge-weather-plus plugin (see https://github.com/simont77/fakegato-history/issues/75)

**Comment by thebodster** [comment]
Apologies, my comment made it sound like the fakegato component was at fault.  As simont77 noted, the actual problem is caused by the eve app becoming stricter.

**Comment by thebodster** [comment]
Updating eve app to version 3.8.3 resolves this issue.  All my history data is now being loaded.

**Comment by naofireblade** [comment]
Thanks for reporting back. So eve kindly changed their app back to the lesser strict homekit services. The issue should be solved then.
