### ISSUE TITLE
Option to display values in Apple home app

### ISSUE THREAD

**Issue by LucasJanin** [naofireblade/homebridge-weather-plus#74]
Hi,

First thanks for this nice plugin, I love to have my exterior temperature without buying a device!
iOS 13 adds new icons like humidity information and  temperature:

https://www.activejr.com/wp-content/uploads/2019/06/HomeKit-iOS-13-new-icons-1493x840.jpg

It will be fantastic if homebridge-weather-plus can be updated!

Thanks

**Comment by naofireblade** [comment]
I'm not sure what's your exact feature request. The icons are automatically assigned by homekit according to the type.
Do you want to see humidity in addition to temperature in the Apple Home App?

**Comment by LucasJanin** [comment]
Hi Naofireblade,

In fact my title was wrong it isn’t just an icon request.
Yes, I can see the humidity in the Apple Home app.

But it looks like it’s possible to add different sensors to a device.
You can see how it’s look like to screen shot attaché to my initial request..
iOS 13 merge them but with iOS 13.2 it’s possible to separate them. 

Thanks by the way for your nice work!

**Comment by naofireblade** [comment]
Sadly the Apple Home app only supports the weather sensors temperature and humidity: https://developer.apple.com/documentation/homekit/hmcharacteristic/characteristic_types

**Comment by naofireblade** [comment]
The next release will have a compatibility mode to display some more characteristics in the home app.

**Comment by LucasJanin** [comment]
Look forward to the new version, Thanks!
