### ISSUE TITLE
Select 2nd observation value for HomeKit display

### ISSUE THREAD

**Issue by RMCob** [naofireblade/homebridge-weather-plus#77]
The Homekit icon displays the current temperature, and if you drill down to the icon settings gear it also displays the current humidity. Would it be possible (perhaps via the currentObservations tag) to specify which value you want for the 2nd observation instead of humidity? In particular I am interested in seeing the atmospheric pressure, but other might want wind speed, etc.
Thanks for a great plugin.

**Comment by naofireblade** [comment]
Sadly the Apple home app does not support other weather characteristics than temperature and humidity. I'm working on a compatibility mode for the home app in the next release.

**Comment by naofireblade** [comment]
Added some unsupported sensors to the Home app with a workaround in the latest beta.
You can test the beta with `npm install -g homebridge-weather-plus@beta`
