### ISSUE TITLE
De-icing cable control

### ISSUE THREAD

**Issue by marcap02** [naofireblade/homebridge-weather-plus#81]
I'd like to control my roof de-icing heat cable but I'm struggling hard to implement a working ruleset. Could you please post a sample configuration or rules which are similar or matching the following criteria?

Turn on heat tape (electrical outlet)
- When snow is in the forecast (ideally 4 - 6 hours before snow starts)
- If temperatures drop below 34F and it was sunny during the day (snow/ice melt)

Turn off:
- One day after the last now did fall
- Temps are above 34F 

Right now I defined:
      {
          "platform": "WeatherPlus",
          "name": "WeatherPlus",
          "service": "darksky",
          "key": "404e2919e42ce7cff3444c9fb8ee160e",
          "locationGeo": [44.991009, -93.002839],
          "forecast": [1,2]
      },

And a rule in eve:
1) Trigger: In 1 day condition category = , scene 'heat tape on'
2) Rigger: Power of outlet =on, condition category in 1 day <=2

But it doesn't work as expected. 

That would help a lot. Thank you!

**Comment by naofireblade** [comment]
Since version 3.0.0 I added two simple sensors for rain / ice in the forecast that should help you.
