### ISSUE TITLE
Occupancy triggers (UV and wind etc)

### ISSUE THREAD

**Issue by rob0101** [naofireblade/homebridge-weather-plus#83]
Is it possible to change the trigger thresholds for these?

e.g. here in Australia, UV > 6 put on sun protection.  > 9 time to get inside.

Thanks for providing this excellent software !

**Comment by naofireblade** [comment]
Good idea. I will add this option in the next release. Glad you like the plugin.

**Comment by sommo** [comment]
Hi! Any news about this feature? It could be very useful to choice when it has to be triggered (in my case) wind speed, to get alert

**Comment by sommo** [comment]
Thank you

**Comment by naofireblade** [comment]
Added in v3.1.0
