### ISSUE TITLE
Siri and dewpoint

### ISSUE THREAD

**Issue by rob0101** [naofireblade/homebridge-weather-plus#84]
I just asked Siri “what is the garden temperature” and was confused by the answer 10 to 15 celsius.

Turns out 10 is the dewpoint.

**Comment by naofireblade** [comment]
Thanks for reporting. Homekit does not support "dewpoint", just temperature. Therefore despite the name "dewpoint" Siri does not know the difference.
You can hide the dewpoint value to solve the problem. See the advanced configuration with the option**hidden**: https://github.com/naofireblade/homebridge-weather-plus/blob/master/README.md#advanced-configuration

**Comment by rob0101** [comment]
I thought as much.  The only place I think it will be an issue is with Siri answering queries, so I'm happy to just leave it and keep the dewpoint tile.
