### ISSUE TITLE
Converting pressure depending on unit system

### ISSUE THREAD

**Issue by netRunner0** [naofireblade/homebridge-weather-plus#87]
Pressure
Can I add a pressure display in millimeters of mercury to the plugin?

If I accidentally changed the name of one of the sensors that contained a colon, how can I go back?

**Comment by naofireblade** [comment]
I will look into converting air pressure depending on the choosen unit system.

If you changed the name manually, I guess you have to delete and re-add the accessory somehow.

**Comment by netRunner0** [comment]
There are no changes in the latest update?

**Comment by naofireblade** [comment]
You can see the changes of each version in the release notes: https://github.com/naofireblade/homebridge-weather-plus/releases

**Comment by naofireblade** [comment]
You can see all code changes here if u are interested: https://github.com/naofireblade/homebridge-weather-plus/compare/v3.0.3...v3.0.4

**Comment by netRunner0** [comment]
I still see the hpa, with the specified SI units

**Comment by naofireblade** [comment]
Who told you otherwise? This ticket is still open and scheduled for version 3.1.0.

**Comment by naofireblade** [comment]
Finally added in v3.1.1 :)
