### ISSUE TITLE
AirPressure value is written in the wrong place

### ISSUE THREAD

**Issue by deryalex96** [naofireblade/homebridge-weather-plus#90]
Hi, I cannot explain it precisely, but
Temperature value is really a value, but Airpressure value is printed in title, not as a value.
I used "home" as "compatibility", since I only use the Apple Home app.

So there is a title eg.: Temperature,
and under there is the value: 9,0°

Humidity
83%

But the value of Air Presure shows nothing, instead the value is in the title, like:
Air Pressure: 1018hPa
and under that, there is nothing.

The same problem appears in UV Index, Wind Dir, Wind Speed.

I hope my explanation was clear enough, I have never posted here.
I am setting up homebridge and just found this issue. 😄

**Comment by naofireblade** [comment]
Hi, that's an issue with homekit itself. The home app only supports temperature and humidity. For everything else I implemented the workaround with the value in the title.

You need to use a 3rd party app like eve if you want to use all the other characteristics in automations etc.
