### ISSUE TITLE
Air Pressure not shown in Homekit

### ISSUE THREAD

**Issue by RMCob** [naofireblade/homebridge-weather-plus#91]
I have been running the latest version for a while. Yesterday I noticed that Air Pressure was no longer being reported in Homekit. (Shows up fine in Eve). What used to say "Air Pressure: 1013hPa now only says "Occupancy sensor". Temp and humidity are shown correctly. When I look at line 277 in index.js it shows where the characteristic is updated with the 'new' name, but that appears to not be happening. 
From my config.json:
{
            "platform": "WeatherPlus",
            "name": "WeatherPlus",
            "service": "openweathermap",
            "key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "displayName": "Outside Temp",
            "units": "us",
            "compatibility": "home",
            "hidden": [
                "WindDirection",
                "WindSpeed",
                "RainBool",
                "SnowBool"
            ],
            "location": 802,
            "locationCity": "Brick, US",
            "locationGeo": [
                40.0707,
                -74.1281
            ]
        }

Let me know what other info you may need. Besides this issue everything else is working fine.
Thanks!

**Comment by naofireblade** [comment]
Did u update anything? iOS on your phone? Do u have a homekit server device like an iPad oder Apple TV?
Another user has the same issue since forever. So one of the devices must prevent the name change.

**Comment by naofireblade** [comment]
Same as #97 still no idea :/ I will leave the other more generic issue open.
