### ISSUE TITLE
No Max Temperature.

### ISSUE THREAD

**Issue by realdannys** [naofireblade/homebridge-weather-plus#92]
I see Temperature Max for today and forecasts should be included but i'm only getting current temp and min temperature. Am I missing something?

**Comment by naofireblade** [comment]
Hi, can you post your config (without api key)?

**Comment by naofireblade** [comment]
Now (current conditions) should have the current temp.
Today (forecast for this day) should have min and max temp.
Tomorrow etc. should have min and max temp.

**Comment by naofireblade** [comment]
Is your question answered?
