### ISSUE TITLE
Request for support of config-ui-x setup options

### ISSUE THREAD

**Issue by tooh** [naofireblade/homebridge-weather-plus#93]
https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI

**Comment by naofireblade** [comment]
I'm almost ready. Need to work out an issue with the config-ui-x author.

Sneak peek:

![image](https://user-images.githubusercontent.com/12081369/74596120-329ada80-504b-11ea-95ce-45763f5d6457.png)

![image](https://user-images.githubusercontent.com/12081369/74596132-4ba38b80-504b-11ea-8ee4-32201999ddd1.png)

**Comment by tooh** [comment]
Looks nice. Thanks for picking this up.

**Comment by naofireblade** [comment]
Added in v3.1.0
