### ISSUE TITLE
Creating automation in EVE app

### ISSUE THREAD

**Issue by nejcklinc** [naofireblade/homebridge-weather-plus#94]
Hi,

can someone tell me how to create automation in EVE app. 
For example I would like to setup an automation like close all my roller shutters if condition is STORM?

Can you please tell me which values are possible for CONDITION category (Dark Spy api) and how to translate numbers to actual condition?
![eve](https://user-images.githubusercontent.com/60596351/73632264-7bba5a00-465b-11ea-9aee-d6f9dcf3ebba.png)

Br, Nejc

**Comment by naofireblade** [comment]
Hi, all weather condition categories are explained here: https://github.com/naofireblade/homebridge-weather-plus#a3

You can set the conditionCategory mode to simple or detailed: https://github.com/naofireblade/homebridge-weather-plus#advanced-configuration

To check for storm you should use the wind speed characteristic in your atuomation.
