### ISSUE TITLE
wunderground not working post Feb 17 outage

### ISSUE THREAD

**Issue by brandoniske** [naofireblade/homebridge-weather-plus#95]
I'm getting the following error in my homebridge debug log upon start up . 

 homebridge-weather-plus Error retrieving weather report and forecast +299ms
 homebridge-weather-plus Error Message: SyntaxError: Unexpected token < in JSON at position 0 +0ms

Temp and humidity are not populating appropriate values. 

I'm on the latest homebridge-weather-plus release - I just updated earlier trying to resolve the issue. Checking my wunderground api account, it is showing under API Key Usage a significant spike in errors today (none previously). I know wunderground had an outage overnight and there was an announcement on their support site which is no longer there. I did see it work earlier today, but now, it's not working at all.

**Comment by WRTHacker** [comment]
Mee too, just install my PWS, all works well, even the myPWS App on IOS.
However there are no data received by this plugin.
Simple config:
"platform": "WeatherPlus",
            "units": "metric",
            "interval": 15,
            "stations": [
                {
                    "displayName": "Lemgo WU",
                    "service": "weatherunderground",
                    "key": "my API key",
                    "stationId": "ILXXXX",
                    "compatibility": "both",
                    "nameNow": "Lemgo jetzt",
                    "now": true,
                    "language": "de"
                }
            ]
        },

**Comment by WRTHacker** [comment]
I don't know why, but now after a further restart, it works ...

**Comment by flausen** [comment]
Hi, I have the same problem, but it doesn‘t work after a few restarts. I have a PWS and a key.

**Comment by flausen** [comment]
Hi, I tested the api via Browser, and all wirkend fine:
https://api.weather.com/v2/pws/observations/current?stationId=IWUNST13&format=json&units=e&apiKey=fea0484870134cc1a04848 (deleted the Last 10 digits). Still got 0 degrees  in Eve or HK

**Comment by naofireblade** [comment]
Ok I will close this issues as it seems to work again. I improved the error logging for Weather Underground in v3.1.2 to be able to investigate future issues better. Feel free to reopen this one or open a new issues if any problems occur.
