### ISSUE TITLE
Request For Installation Support on HOOBS

### ISSUE THREAD

**Issue by a-rodriguez** [naofireblade/homebridge-weather-plus#96]
Would like to ability to install on HOOBS https://hoobs.org. When I search for homebridge-weather-plus it returns another plugin by the same name. I have Meteobridge connected to my station.

**Comment by askovi** [comment]
This plugins works fine on HOOBS. The search returns this plugin exactly. Just search for weather plus

**Comment by a-rodriguez** [comment]
> This plugins works fine on HOOBS. The search returns this plugin exactly. Just search for weather plus

I don't believe the search is returning this plugin exactly. HOOBS search is returning https://github.com/naofireblade/homebridge-weather-plus, that is not the same plugin as this one. This one is https://github.com/MikeManzo/homebridge-weather-plus, I believe its a fork of the ones HOOBS is finding. The primary reason I want this plugin is its support for Meteobridge.

**Comment by naofireblade** [comment]
Askovi is correct. This is homebridge-weather-plus from naofireblade (me). The one from MikeManzo is the forked one, that added meteobridge support. You could ask MikeManzo to submit a pull request to add the meteobridge support into this plugin.
