### ISSUE TITLE
Add uv index to OpenWeatherMap API

### ISSUE THREAD

**Issue by raphaeldavid** [naofireblade/homebridge-weather-plus#99]
This is my config

        {
            "units": "ca",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "xxxx",
                    "service": "openweathermap",
                    "key": "xxxxxxxxx",
                    "locationGeo": [
                        xx.xxxx,
                        -xx.xxxx
                    ],
                    "locationId": xxxx,
                    "locationCity": "xxxx",
                    "language": "fr",
                    "compatibility": "both",
                    "conditionCategory": "detailed",
                    "now": true,
                    "extraHumidity": false,
                    "tresholdAirPressure": 1025,
                    "tresholdUvIndex": 5,
                    "tresholdWindSpeed": 50
                }
            ],
            "platform": "WeatherPlus"
        }

**Comment by naofireblade** [comment]
UV Index is currently only available for darksky. I will add this for OpenWeatherMap in an upcoming release.

**Comment by naofireblade** [comment]
see #114

**Comment by naofireblade** [comment]
Added uvindex in latest beta. You can install the beta with:

`npm install -g homebridge-weather-plus@beta`
